FROM python:3.7.2-slim
# HEGP NECKER
#special variables to define in order to process
#and generate the provenance of the script

MAINTAINER william.digan@aphp.fr

WORKDIR /home
RUN mkdir src data
RUN apt-get update
RUN apt-get -y install g++ gcc git
# RUN pip3 install -r /home/src/pymedext/requirements.txt

RUN apt-get update && apt-get install -y --allow-unauthenticated procps
COPY .git-credentials /root/
RUN git config --global credential.helper store --file=/root/.git-credentials
RUN pip3 install git+https://github.com/equipe22/pymedext_core.git
WORKDIR /home/src
RUN git clone https://github.com/equipe22/pymedext_eds.git
WORKDIR /home/src/pymedext_eds
RUN apt-get install -y python3-dev libevent-dev
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install -r requirements.txt
RUN pip3 install git+https://github.com/equipe22/pymedext_eds.git@master#egg=pymedext_eds

# RUN pip3 install SPARQLWrapper
# ADD ressources/ /home/src/ressources/
# COPY lower_output.RRF src/
COPY eds_app /home/src/eds_app
RUN cp list_regexp.json /home/src/eds_app
WORKDIR /home/src/eds_app/
RUN rm /root/.git-credentials
# COPY bin/installstopword.py .
# RUN python3 installstopword.py
expose 6666
CMD ["python3", " /home/src/eds_app/demo_flask.py "]
