SECTION_DICT = {
    'antecedent': ['ANTECEDENTS MEDICAUX',
                'ANTÉCÉDENTS',
                'Antécédents médicaux et chirurgicaux',
                'ANTECEDENTS et HISTOIRE DE LA MALADIE',
                'ATCD:',
                'Antécédents chirurgicaux :',
                'Antécédent :',
                'Principaux antécédents et problèmes médicaux actuellement '
                'posés par le patient',
                'Allergie :',
                'ATCD med:',
                'Antécédents médicaux :',
                '4/ Antécédents, Autre(s) Maladie(s) en cours, Habitus, Mode '
                'de vie :',
                'Antécédents:',
                'Antécédents personnels',
                'Rappel des antécédents :',
                'Allergies',
                'Antécédents',
                'Principaux antécédents',
                'Allergies :',
                'FACTEURS DE RISQUES',
                'ANTÉCÉDENTS PERSONNELS',
                'ANTECEDENTS :',
                'RAPPEL DES ANTÉCÉDENTS ET HISTOIRE DE LA MALADIE',
                'FACTEURS DE RISQUE CARDIOVASCULAIRE :',
                'Facteurs de risque',
                'ANTECEDENTS ET PATHOLOGIES CHRONIQUES',
                'RESUME DES ANTECEDENTS',
                'ANTECEDENTS',
                'FACTEURS DE RISQUE CARDIOVASCULAIRES :',
                'ANTÉCÉDENTS MÉDICAUX ET CHIRURGICAUX',
                'ANTÉCÉDENTS :',
                'antécédents',
                'Facteurs de risque:',
                'ATCD :',
                'Facteurs de risques',
                'ANTECEDENTS PERSONNELS',
                'Antécédents somatiques :',
                'PRINCIPAUX ANTECEDENTS MEDICAUX et CHIRURGICAUX :',
                'Antécédents personnels :',
                'ATCD GYNECO:',
                'Antécédents :'],
 'antecedent_familiaux': ['Antécédents familiaux',
                          'Antécédent familial :',
                          'Antécédents familiaux :',
                          'ANTÉCÉDENTS FAMILIAUX'],
 'autre': ['INTERVENTION',
           'ANALYSE',
           'Rendez-vous de consultation post-opératoire :',
           'Pour mémoire :',
           'Réeducation à prévoir',
           'Médecin :',
           'ECG :',
           'Synthèse médicale :',
           'Service Demandeur :',
           'Évènements récents',
           'Planification des soins',
           'Synthèse clinico-biologique :',
           'PROJET DIAGNOSTIQUE ET THÉRAPEUTIQUE',
           'MODE DE SORTIE',
           'Résultat de la coronarographie',
           'Modifications thérapeutiques :',
           'ENQUETE DIETETIQUE :',
           'Suites opératoires :',
           'DEPISTAGES :',
           'Analyse',
           'hospitalisé dans le service de NEUROLOGIE_ADUL pour :',
           'Soins infirmiers',
           'Synthèse',
           'Prochains rendez-vous',
           'ÉVÉNEMENTS RÉCENTS',
           'SUIVI',
           'TSH :',
           'REEDUCATION-READAPTATION :',
           'DIAGNSOTICS REALISES AU COURS DE L’HOSPITALISATION :',
           'Synthèse initiale',
           'Contrôles biologiques :',
           "Technique d'enregistrement",
           'SUITES OPERATOIRES :',
           "A l'interrogatoire :",
           'OBJECTIFS GENERAUX DE LA PRISE EN CHARGE',
           'Appareillage',
           'HEMOPATHIE',
           'Evénement intercurrent',
           'Sommeil actuel',
           'TTT:',
           'Avis spécialisé',
           'Radiographie de contrôle :',
           'Développement psychomoteur',
           'Sérologies vaccinales',
           'Poids de sortie',
           'Chirurgicaux :',
           'Correspondant :',
           'EVENEMENTS RECENTS',
           'ENQUETE ACTIVITE PHYSIQUE :',
           'Résumé observation :',
           'Hospitalisations :',
           'Actes réalisés :',
           'SUITES POSTOPERATOIRES',
           'Destination de sortie',
           'Pathologies actives :',
           "Déroulement et résultat de l'angioplastie",
           'ENQUÊTE ACTIVITÉ PHYSIQUE :',
           "Indication de l'acte",
           'Mots clés :',
           'Résultats biologiques :',
           'NFS DE SORTIE',
           'ENTREE',
           'SUR LE PLAN PSYCHOLOGIQUE :',
           'CONTRÔLES SEROLOGIQUES :',
           'Kinésithérapie :',
           'SYNTHESE MEDICALE DIAGNOSTIQUE ET THERAPEUTIQUE :',
           'SYNTHESE MEDICALE',
           'INTERPRETATION',
           'Événements depuis la dernière visite',
           'INTERVENTION CHIRURGICALE :',
           'Documents de sortie',
           'Aux urgences:',
           'PLANIFICATION DES RENDEZ-VOUS',
           'PLANIFICATION DES SOINS / SUITES À DONNER',
           'PROCEDURE PRE-THERAPEUTIQUE',
           'PRISE EN CHARGE',
           'Synthèse générale',
           'INTERVENTION :',
           'Copie à :',
           'RESUME',
           'Suivi',
           'Technique',
           'INTERCURE',
           "Scores à l'entrée",
           'PMSI',
           'Familiaux',
           "L'ensemble des explorations réalisées ce jour retrouve :",
           'Evénements recensés au cours de ce séjour :',
           "Prise en charge à l'admission",
           'Pathologies intercurrentes :',
           'Signes fonctionnels',
           'Intervention(s) - acte(s) réalisé(s) :',
           'Contexte familial et social',
           'Mensurations de sortie',
           'Prise en charge :',
           'SUITES PREVUES :',
           'Actes réalisés',
           'PROJET THÉRAPEUTIQUE',
           'C ONDUITE THÉRAPEUTIQU E',
           'PROBLEMES PRIS EN CHARGE DANS LE SERVICE',
           'Projet thérapeutique à la sortie',
           'EVALUATION SOCIALE',
           'DESCRIPTION DETAILLEE',
           'Conseils',
           'Attitude thérapeutique initiale',
           "COMPTE-RENDU D'HOSPITALISATION :",
           'Dépistages',
           "A l'arrivée dans le service",
           'Nutrition',
           'PROPOSITION DE LA RCP',
           'Grossesse - Période néonatale',
           'Développement pubertaire',
           'ENQUÊTE DIÉTÉTIQUE :',
           'OBSERVATION',
           'POSE DE CATHETER CENTRAL',
           'Indication :',
           'STATUT FONCTIONNEL DE SORTIE',
           'Score de tri :',
           'Synthèse de la réeducation',
           'Projet thérapeutique',
           'SUIVI POSTOPERATOIRE :',
           'Interprétation :',
           'PROJET THERAPEUTIQUE',
           'Exploration du sommeil',
           'SYNTHÈSE MÉDICALE',
           'Données générales',
           'Orientation',
           'Croissance staturo-pondérale',
           'A son arrivée',
           'CORRESPONDANTS',
           'Points à surveiller',
           'Scores à la sortie'],
 'conclusion': ['SYNTÈSE MÉDICALE / CONCLUSION',
                'CONCLUSION :',
                'SYNTHESE MEDICALE/CONCLUSION',
                'Concl:',
                'Diagnostics :',
                'DIAGNOSTIC :',
                'CONSIGNES POST OP :',
                'Au total:',
                'Diagnostics retenus',
                'CONCLUSION DE SORTIE',
                'Au total :',
                'AU TOTAL',
                'Conclusion de sortie',
                'CONDUITE THÉRAPEUTIQUE :',
                'Diagnostic :',
                'Conduite à tenir :',
                'Diagnostics',
                'CAT:',
                'AU TOTAL :',
                "Conclusion à l'entrée",
                'Conclusion',
                'CONCLUSION D’ENTRÉE :',
                'Au total',
                'CONSIGNES A LA SORTIE',
                'AU TOTAL:',
                'DIAGNOSTIC RETENUS',
                'CONDUITE PRATIQUE :',
                'Diagnostic retenu',
                'DIAGNOSTIC',
                'CONCLUSION',
                'CAT :',
                'Conclusion :',
                'Diagnostics de sortie'],
 'evolution': ['Evolution dans le service:',
               'Evolution depuis la dernière consultation',
               'EVOLUTION DANS LE SERVICE',
               'EVOLUTION et CONCLUSION',
               'EVOLUTION',
               'ÉVOLUTION',
               'SUITES OPERATOIRES / EVOLUTION DANS LE SERVICE',
               'Evolution :',
               'Evolution dans le Service',
               'EVOLUTION :',
               'ÉVOLUTION :',
               'Evolution dans le service',
               'Evolution dans le service :',
               'Evolution',
               "Evolution durant l'hospitalisation"],
 'examen_clinique': ['Examen clinique',
                     "EXAMEN CLINIQUE A L'ENTRÉE",
                     "Examen clinique à l'arrivée",
                     "PARAMÈTRES VITAUX ET DONNÉES BIOMÉTRIQUES À L'ENTRÉE",
                     "Résultats d'examens",
                     'RAPPEL\nCLINIQUE',
                     'Résumé clinique :',
                     'Examens prescrits :',
                     'Examen clinique :',
                     'LE BILAN CLINIQUE AUX URGENCES A MONTRÉ :',
                     "Examen clinique à l'entrée :",
                     'Cliniquement :',
                     "Examen clinique à l'admission :",
                     "Paramètres vitaux, à l'accueil :",
                     "Données biométriques à l'entrée",
                     "EXAMEN CLINIQUE A L'ENTREE",
                     "PARAMÈTRES VITAUX ET DONNÉES BIOMÉTRIQUES A L'ENTRÉE",
                     'EXAMEN CLINIQUE :',
                     'Constantes de sortie :',
                     "Examen clinique à l'entrée",
                     "Données Biométriques à l'entrée",
                     'EXAMENS BIOLOGIQUES',
                     "Données biomètriques et paramètres vitaux à l'entrée",
                     'Examen clinique initial :',
                     'Examens para-cliniques',
                     "Paramètres vitaux à l'entrée",
                     'Clinique actuelle:',
                     'EXAMEN',
                     'Rappel clinique :',
                     'CONSTANTES DE SORTIE',
                     "EXAMEN CLINIQUE A L'ARRIVEE",
                     "EXAMEN CLINIQUE À L'ENTRÉE",
                     'Particularités cliniques et paracliniques',
                     "A L'EXAMEN CLINIQUE :",
                     'RAPPEL CLINIQUE:',
                     "Données biométriques et paramètres vitaux à l'entrée",
                     'Examen paraclinique :',
                     'Examen clinique :(?)',
                     "EXAMEN CLINIQUE À L'ARRIVÉE",
                     'La dernière évaluation clinique',
                     'Examen\nclinique :',
                     'A l’examen ce jour',
                     "Paramètres vitaux à l'accueil des urgences :",
                     'Examen clinique initial',
                     'Evolution clinique récente :',
                     'RAPPEL CLINIQUE',
                     'EXAMEN INITIAL :',
                     'DONNEES CLINIQUES',
                     "EXAMEN A L'ENTREE",
                     'Résumé clinique',
                     'Auscultation',
                     'EXAMEN CLINIQUE',
                     'A l’examen :',
                     'Clinique :',
                     "PARAMETRES VITAUX ET DONNEES BIOMETRIQUES A L'ENTREE",
                     'RAPPEL CLINIQUE :',
                     'Examen de sortie',
                     'CLINIQUE'],
 'examen_complementaire': ["Examens complémentaires à l'entrée",
                           'Biologie:',
                           'Biologie :',
                           'Examens complémentaires au cours du séjour',
                           'Autres examens complémentaires et évolution',
                           'Examen(s) complémentaire(s) :',
                           'EXAMENS COMPLEMENTAIRES',
                           'Bilan nutritionnel :',
                           'Examen complémentaire :',
                           'EXAMENS COMPLÉMENTAIRES RÉALISÉS PENDANT LE SÉJOUR',
                           'BILAN BIOLOGIQUE :',
                           'EXAMENS COMPLÉMENTAIRES',
                           "Bilan biologique à l'entrée",
                           'Biologie à l’entrée',
                           'EXAMEN COMPLEMENTAIRE',
                           'BIOCHIMIE',
                           'Examens complémentaires :',
                           'RADIOLOGIE :',
                           'Bilan extension :',
                           "Autres examens complémentaires à l'entrée",
                           'IMAGERIE :',
                           'BILAN PRÉOPÉRATOIRE :',
                           'EXAMENS COMPLÉMENTAIRES :',
                           'Bilan biologique :',
                           'BIOLOGIE :',
                           'Examens complémentaires',
                           "Résultats du bilan d'opérabilité :",
                           'EXAMENS COMPLEMENTAIRES :'],
 'histoire': ['Histoire récente de la maladie',
              'Histoire de la maladie actuelle',
              'HISTOIRE DU POIDS :',
              'Histoire de la maladie - Explorations',
              '5/ Histoire de la maladie',
              'Histoire récente',
              'HISTOIRE RECENTE',
              'Anamnèse',
              'HDM',
              'HISTOIRE DU DIABÈTE :',
              'Histoire de la Maladie:',
              'Histoire succincte de la maladie :',
              'ANAMNESE',
              'Histoire de la maladie :',
              'HDM:',
              '5/Histoire de la maladie :',
              'HISTOIRE RESUMEE DE LA MALADIE',
              'Histoire :',
              'HISTOIRE DU DIABETE :',
              "Résumé de l'histoire de la maladie",
              'HISTOIRE RECENTE MOTIVANT L’HOSPITALISATION',
              'HDM :',
              'Histoire de la maladie',
              'HISTOIRE RECENTE DE LA MALADIE :',
              'Histoire de la Maladie :',
              'HISTOIRE DE LA MALADIE'],
 'mode_de_vie': ['MODE DE VIE :',
                 'Mode de vie - Scolarité',
                 'MODE DE VIE',
                 'Mode de vie',
                 'HABITUS',
                 'Situation sociale, mode de vie',
                 'HABITUS :',
                 'Mode de vie :',
                 'Mode de vie antérieur :',
                 'Habitus'],
 'motif': ['Motif médical',
           "MOTIF DE L'EXAMEN",
           "motif d'hospitalisation:",
           "MOTIF DE L'EXAMEN :",
           'MOTIF',
           "MOTIF D'INTERVENTION",
           "Motif de l'hospitalisation",
           "MOTIF D'HOSPITALISATION :",
           'Motif de consultation :',
           'Motif de tri :',
           'Motif de la consultation :',
           "Motif d'Hospitalisation :",
           "MOTIF D'HOSPITALISATION",
           "MOTIF DE L'HOSPITALISATION :",
           "Motif d'hospitalisation",
           'MOTIF D’HOSPITALISATION :',
           'motif suivant :',
           "Motif de l'hospitalisation :",
           "Motif de l'examen",
           'Motif :',
           'Motif de la première consultation',
           'MOTIF d’HOSPITALISATION :',
           'MOTIF :',
           'Motif d’hospitalisation :',
           'Motif'],
 'traitement': ['Traitements :',
                'Demandes et prescriptions externes',
                'Prescriptions aux urgences',
                'TRAITEMENTS :',
                'Traitements associés',
                'TRAITEMENT :',
                'Traitement',
                'PROTOCOLE DE TRAITEMENT',
                'Traitement :'],
 'traitement_entree': ["TRAITEMENT A L'ENTRAÉE",
                       'TRAITEMENTS HABITUELS:',
                       'Vaccinations :',
                       'Traitement en cours :',
                       'Vaccinations',
                       'Traitement depuis la dernière visite',
                       'TRAITEMENTS A L’ENTREE',
                       'Traitement au domicile :',
                       "TRAITEMENT D'ENTRÉE :",
                       'TRAITEMENT A L’ARRIVEE',
                       "TRAITEMENT À L'ENTRÉE",
                       'Traitement en cours',
                       'TRAITEMENT ACTUEL :',
                       'Traitements en cours :',
                       "TRAITEMENT A L'ENTREE",
                       'Traitement actuel',
                       'Traitements habituels :',
                       'TRAITEMENT EN COURS',
                       "TRAITEMENT A L'ENTRÉE",
                       "Traitement à l'entrée:",
                       "Traitements à l'entrée",
                       "Traitement d'entrée :",
                       'TRAITEMENT HABITUEL :',
                       'Traitements actuels',
                       'VACCINATIONS :',
                       "Traitement à l'entrée",
                       'Traitement actuel :',
                       'VACCINATIONS',
                       'Traitement habituel :',
                       'Traitements habituels',
                       'TRAITEMENT HABITUEL'],
 'traitement_sortie': ['TRAITEMENT DE SORTIE',
                       "Traitement à l'issue de la consultation",
                       'Prescriptions médicales de sortie',
                       'Traitement de sortie',
                       'Prescriptions médicales de sortie :',
                       'Traitement de sortie :',
                       'Traitement et consignes de sortie :',
                       'Prescriptions de sortie :']}


#########################################################################

CLASS_NORM = {
 '5 ASA': ['A07EC02 (MESALAZINE)'],
 'AAP': ["B01AC (INHIBITEURS DE L'AGREGATION PLAQUETTAIRE, HEPARINE EXCLUE)"],
 'ABVD': ['L01AX04 (DACARBAZINE)'],
 'ACIDE FOLIQUE': ['B03BB01 (FOLIQUE ACIDE)'],
 'AEROSOL BRONCHODILATATEURS': ['R03A (ADRENERGIQUES POUR INHALATION)',
                                'R03B (AUTRES MEDICAMENTS POUR LES SYNDROMES '
                                'OBSTRUCTIFS DES VOIES AERIENNES, PAR '
                                'INHALATION)'],
 'AINS': ['S01BC (ANTIINFLAMMATOIRES NON STEROIDIENS)'],
 'ALBUMINE': ['B05AA01 (ALBUMINE)'],
 'ALIMENTATION PARENTERALE': ['B05BA (SOLUTIONS POUR NUTRITION PARENTERALE)'],
 'ALPHA BLOQUANT': ['G04CA (ALPHA-BLOQUANTS)', 'C02CA (ALPHA-BLOQUANTS)'],
 'ALPHA BLOQUANTS': ['G04CA (ALPHA-BLOQUANTS)', 'C02CA (ALPHA-BLOQUANTS)'],
 'ALPHABLOQUANT': ['G04CA (ALPHA-BLOQUANTS)', 'C02CA (ALPHA-BLOQUANTS)'],
 'ANALGESIE': ['N02A (OPIOIDES)',
               'N02B (AUTRES ANALGESIQUES ET ANTIPYRETIQUES)',
               'N02C (ANTIMIGRAINEUX)'],
 'ANESTHESIE GENERALE': ['N01A (ANESTHESIQUES GENERAUX)'],
 'ANESTHESIE LOCALE': ['N01B (ANESTHESIQUES LOCAUX)',
                       'S01H (ANESTHESIQUES LOCAUX)'],
 'ANTALGIE': ['N02A (OPIOIDES)',
              'N02B (AUTRES ANALGESIQUES ET ANTIPYRETIQUES)',
              'N02C (ANTIMIGRAINEUX)'],
 'ANTALGIQUES': ['N02A (OPIOIDES)',
                 'N02B (AUTRES ANALGESIQUES ET ANTIPYRETIQUES)',
                 'N02C (ANTIMIGRAINEUX)'],
 'ANTHRACYCLINES': ['J01A (TETRACYCLINES)'],
 'ANTI AGGREGATION': ["B01AC (INHIBITEURS DE L'AGREGATION PLAQUETTAIRE, "
                      'HEPARINE EXCLUE)'],
 'ANTI AGREGANT': ["B01AC (INHIBITEURS DE L'AGREGATION PLAQUETTAIRE, HEPARINE "
                   'EXCLUE)'],
 'ANTI AGREGANTS': ["B01AC (INHIBITEURS DE L'AGREGATION PLAQUETTAIRE, HEPARINE "
                    'EXCLUE)'],
 'ANTI AGREGATION': ["B01AC (INHIBITEURS DE L'AGREGATION PLAQUETTAIRE, "
                     'HEPARINE EXCLUE)'],
 'ANTI AGREGATION PLAQUETTAIRE': ["B01AC (INHIBITEURS DE L'AGREGATION "
                                  'PLAQUETTAIRE, HEPARINE EXCLUE)'],
 'ANTI ARYTHMIQUE': ['C01B (ANTIARYTHMIQUES, CLASSE I ET III)'],
 'ANTI CALCINEURINES': ['H05BA (CALCITONINES)'],
 'ANTI CHOLINERGIQUE': ['N04A (ANTICHOLINERGIQUES)'],
 'ANTI DEPRESSEURS': ['N06A (ANTIDEPRESSEURS)'],
 'ANTI DIABETIQUES': ['A10B (ANTIDIABETIQUES, INSULINES EXCLUES)',
                      'A10A (INSULINES ET ANALOGUES)'],
 'ANTI EMETIQUE': ['A04A (ANTIEMETIQUES ET ANTINAUSEEUX)'],
 'ANTI EMETIQUES': ['A04A (ANTIEMETIQUES ET ANTINAUSEEUX)'],
 'ANTI H1': ['R06A (ANTIHISTAMINIQUES A USAGE SYSTEMIQUE)'],
 'ANTI HISTAMINIQUE': ['R06A (ANTIHISTAMINIQUES A USAGE SYSTEMIQUE)'],
 'ANTI HISTAMINIQUES': ['R06A (ANTIHISTAMINIQUES A USAGE SYSTEMIQUE)'],
 'ANTI HTA': ['C02K (AUTRES ANTIHYPERTENSEURS)',
              'C02C (ADRENOLYTIQUES A ACTION PERIPHERIQUE)',
              'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
              'C02D (MEDICAMENTS AGISSANT SUR LE MUSCLE LISSE ARTERIOLAIRE)',
              'C02L (ANTIHYPERTENSEURS ET DIURETIQUES EN ASSOCIATION)'],
 'ANTI HYPERTENSEUR': ['C02K (AUTRES ANTIHYPERTENSEURS)',
                       'C02C (ADRENOLYTIQUES A ACTION PERIPHERIQUE)',
                       'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
                       'C02D (MEDICAMENTS AGISSANT SUR LE MUSCLE LISSE '
                       'ARTERIOLAIRE)',
                       'C02L (ANTIHYPERTENSEURS ET DIURETIQUES EN '
                       'ASSOCIATION)'],
 'ANTI HYPERTENSEURS': ['C02K (AUTRES ANTIHYPERTENSEURS)',
                        'C02C (ADRENOLYTIQUES A ACTION PERIPHERIQUE)',
                        'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
                        'C02D (MEDICAMENTS AGISSANT SUR LE MUSCLE LISSE '
                        'ARTERIOLAIRE)',
                        'C02L (ANTIHYPERTENSEURS ET DIURETIQUES EN '
                        'ASSOCIATION)'],
 'ANTI INFECTIEUX': ['S01A (ANTIINFECTIEUX)', 'S02A (ANTIINFECTIEUX)'],
 'ANTI INFLAMMATOIRE': ['S01B (ANTIINFLAMMATOIRES)'],
 'ANTI INFLAMMATOIRE NON STEROIDIENS': ['S01BC (ANTIINFLAMMATOIRES NON '
                                        'STEROIDIENS)'],
 'ANTI INFLAMMATOIRES': ['S01B (ANTIINFLAMMATOIRES)'],
 'ANTI PD1': ['S01A (ANTIINFECTIEUX)'],
 'ANTI TNF': ['L04AB (INHIBITEURS DU FACTEUR NECROSANT DES TUMEURS ALFA (TNF '
              'ALFA))'],
 'ANTI TNF ALPHA': ['L04AB (INHIBITEURS DU FACTEUR NECROSANT DES TUMEURS ALFA '
                    '(TNF ALFA))'],
 'ANTI VITAMINE K': ['B01AA (ANTIVITAMINES K)'],
 'ANTIAGGREGATION': ["B01AC (INHIBITEURS DE L'AGREGATION PLAQUETTAIRE, "
                     'HEPARINE EXCLUE)'],
 'ANTIAGREGANT': ["B01AC (INHIBITEURS DE L'AGREGATION PLAQUETTAIRE, HEPARINE "
                  'EXCLUE)'],
 'ANTIAGREGANT PLAQUETTAIRE': ["B01AC (INHIBITEURS DE L'AGREGATION "
                               'PLAQUETTAIRE, HEPARINE EXCLUE)'],
 'ANTIAGREGANTS': ["B01AC (INHIBITEURS DE L'AGREGATION PLAQUETTAIRE, HEPARINE "
                   'EXCLUE)'],
 'ANTIAGREGATION': ["B01AC (INHIBITEURS DE L'AGREGATION PLAQUETTAIRE, HEPARINE "
                    'EXCLUE)'],
 'ANTIAGREGATION PLAQUETTAIRE': ["B01AC (INHIBITEURS DE L'AGREGATION "
                                 'PLAQUETTAIRE, HEPARINE EXCLUE)'],
 'ANTIBIO': ['J01C (BETALACTAMINES : PENICILLINES)',
             'J01X (AUTRES ANTIBACTERIENS)',
             'J01D (AUTRES BETALACTAMINES)',
             'J01M (QUINOLONES ANTIBACTERIENNES)',
             'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
             'J01A (TETRACYCLINES)',
             'J01E (SULFAMIDES ET TRIMETHOPRIME)',
             'J01G (AMINOSIDES ANTIBACTERIENS)',
             "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
             'J01B (PHENICOLES)'],
 'ANTIBIOTHERAPIE': ['J01C (BETALACTAMINES : PENICILLINES)',
                     'J01X (AUTRES ANTIBACTERIENS)',
                     'J01D (AUTRES BETALACTAMINES)',
                     'J01M (QUINOLONES ANTIBACTERIENNES)',
                     'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
                     'J01A (TETRACYCLINES)',
                     'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                     'J01G (AMINOSIDES ANTIBACTERIENS)',
                     "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                     'J01B (PHENICOLES)'],
 'ANTIBIOTHERAPIE EMPIRIQUE': ['J01C (BETALACTAMINES : PENICILLINES)',
                               'J01X (AUTRES ANTIBACTERIENS)',
                               'J01D (AUTRES BETALACTAMINES)',
                               'J01M (QUINOLONES ANTIBACTERIENNES)',
                               'J01F (MACROLIDES, LINCOSAMIDES  ET '
                               'STREPTOGRAMINES)',
                               'J01A (TETRACYCLINES)',
                               'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                               'J01G (AMINOSIDES ANTIBACTERIENS)',
                               "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                               'J01B (PHENICOLES)'],
 'ANTIBIOTHERAPIEA': ['J01C (BETALACTAMINES : PENICILLINES)',
                      'J01X (AUTRES ANTIBACTERIENS)',
                      'J01D (AUTRES BETALACTAMINES)',
                      'J01M (QUINOLONES ANTIBACTERIENNES)',
                      'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
                      'J01A (TETRACYCLINES)',
                      'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                      'J01G (AMINOSIDES ANTIBACTERIENS)',
                      "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                      'J01B (PHENICOLES)'],
 'ANTIBIOTHERAPIEEN': ['J01C (BETALACTAMINES : PENICILLINES)',
                       'J01X (AUTRES ANTIBACTERIENS)',
                       'J01D (AUTRES BETALACTAMINES)',
                       'J01M (QUINOLONES ANTIBACTERIENNES)',
                       'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
                       'J01A (TETRACYCLINES)',
                       'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                       'J01G (AMINOSIDES ANTIBACTERIENS)',
                       "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                       'J01B (PHENICOLES)'],
 'ANTIBIOTHERAPIEET': ['J01C (BETALACTAMINES : PENICILLINES)',
                       'J01X (AUTRES ANTIBACTERIENS)',
                       'J01D (AUTRES BETALACTAMINES)',
                       'J01M (QUINOLONES ANTIBACTERIENNES)',
                       'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
                       'J01A (TETRACYCLINES)',
                       'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                       'J01G (AMINOSIDES ANTIBACTERIENS)',
                       "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                       'J01B (PHENICOLES)'],
 'ANTIBIOTHERAPIEPAR': ['J01C (BETALACTAMINES : PENICILLINES)',
                        'J01X (AUTRES ANTIBACTERIENS)',
                        'J01D (AUTRES BETALACTAMINES)',
                        'J01M (QUINOLONES ANTIBACTERIENNES)',
                        'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
                        'J01A (TETRACYCLINES)',
                        'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                        'J01G (AMINOSIDES ANTIBACTERIENS)',
                        "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                        'J01B (PHENICOLES)'],
 'ANTIBIOTHERAPIEPROBABILISTE': ['J01C (BETALACTAMINES : PENICILLINES)',
                                 'J01X (AUTRES ANTIBACTERIENS)',
                                 'J01D (AUTRES BETALACTAMINES)',
                                 'J01M (QUINOLONES ANTIBACTERIENNES)',
                                 'J01F (MACROLIDES, LINCOSAMIDES  ET '
                                 'STREPTOGRAMINES)',
                                 'J01A (TETRACYCLINES)',
                                 'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                                 'J01G (AMINOSIDES ANTIBACTERIENS)',
                                 "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                                 'J01B (PHENICOLES)'],
 'ANTIBIOTHERAPIEPROBABILISTEPAR': ['J01C (BETALACTAMINES : PENICILLINES)',
                                    'J01X (AUTRES ANTIBACTERIENS)',
                                    'J01D (AUTRES BETALACTAMINES)',
                                    'J01M (QUINOLONES ANTIBACTERIENNES)',
                                    'J01F (MACROLIDES, LINCOSAMIDES  ET '
                                    'STREPTOGRAMINES)',
                                    'J01A (TETRACYCLINES)',
                                    'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                                    'J01G (AMINOSIDES ANTIBACTERIENS)',
                                    "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                                    'J01B (PHENICOLES)'],
 'ANTIBIOTHERAPIES': ['J01C (BETALACTAMINES : PENICILLINES)',
                      'J01X (AUTRES ANTIBACTERIENS)',
                      'J01D (AUTRES BETALACTAMINES)',
                      'J01M (QUINOLONES ANTIBACTERIENNES)',
                      'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
                      'J01A (TETRACYCLINES)',
                      'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                      'J01G (AMINOSIDES ANTIBACTERIENS)',
                      "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                      'J01B (PHENICOLES)'],
 'ANTIBIOTIQUE': ['J04AB (ANTIBIOTIQUES)',
                  'S01AA (ANTIBIOTIQUES)',
                  'J02AA (ANTIBIOTIQUES)',
                  'A07AA (ANTIBIOTIQUES)',
                  'G01AA (ANTIBIOTIQUES)'],
 'ANTIBIOTIQUE AMINOSIDES': ['J01G (AMINOSIDES ANTIBACTERIENS)'],
 'ANTIBIOTIQUES': ['J04AB (ANTIBIOTIQUES)',
                   'S01AA (ANTIBIOTIQUES)',
                   'J02AA (ANTIBIOTIQUES)',
                   'A07AA (ANTIBIOTIQUES)',
                   'G01AA (ANTIBIOTIQUES)'],
 'ANTICALCINEURINES': ['L04AD (INHIBITEURS DE LA CALCINEURINE)'],
 'ANTICHOLINERGIQUE': ['N04A (ANTICHOLINERGIQUES)'],
 'ANTICHOLINERGIQUES': ['N04A (ANTICHOLINERGIQUES)'],
 'ANTICOAGULANT': ['B01AA (ANTIVITAMINES K)',
                   "B01AB (GROUPE DE L'HEPARINE)",
                   'B01AE (INHIBITEURS DIRECTS DE LA THROMBINE)',
                   'B01AF (INHIBITEURS DIRECTS DU FACTEUR Xa)',
                   'B01AX (AUTRES ANTITHROMBOTIQUES)'],
 'ANTICOAGULANTS': ['B01AA (ANTIVITAMINES K)',
                    "B01AB (GROUPE DE L'HEPARINE)",
                    'B01AE (INHIBITEURS DIRECTS DE LA THROMBINE)',
                    'B01AF (INHIBITEURS DIRECTS DU FACTEUR Xa)',
                    'B01AX (AUTRES ANTITHROMBOTIQUES)'],
 'ANTICOAGULATION': ['B01AA (ANTIVITAMINES K)',
                     "B01AB (GROUPE DE L'HEPARINE)",
                     'B01AE (INHIBITEURS DIRECTS DE LA THROMBINE)',
                     'B01AF (INHIBITEURS DIRECTS DU FACTEUR Xa)',
                     'B01AX (AUTRES ANTITHROMBOTIQUES)'],
 'ANTICOAGULATION CURATIVE': ['B01AA (ANTIVITAMINES K)',
                              "B01AB (GROUPE DE L'HEPARINE)",
                              'B01AE (INHIBITEURS DIRECTS DE LA THROMBINE)',
                              'B01AF (INHIBITEURS DIRECTS DU FACTEUR Xa)',
                              'B01AX (AUTRES ANTITHROMBOTIQUES)'],
 'ANTICOAGULATION PREVENTIVE': ['B01AA (ANTIVITAMINES K)',
                                "B01AB (GROUPE DE L'HEPARINE)",
                                'B01AE (INHIBITEURS DIRECTS DE LA THROMBINE)',
                                'B01AF (INHIBITEURS DIRECTS DU FACTEUR Xa)',
                                'B01AX (AUTRES ANTITHROMBOTIQUES)'],
 'ANTICOAGULATIONCURATIVE': ['B01AA (ANTIVITAMINES K)',
                             "B01AB (GROUPE DE L'HEPARINE)",
                             'B01AE (INHIBITEURS DIRECTS DE LA THROMBINE)',
                             'B01AF (INHIBITEURS DIRECTS DU FACTEUR Xa)',
                             'B01AX (AUTRES ANTITHROMBOTIQUES)'],
 'ANTICOAGULATIONEFFICACE': ['B01AA (ANTIVITAMINES K)',
                             "B01AB (GROUPE DE L'HEPARINE)",
                             'B01AE (INHIBITEURS DIRECTS DE LA THROMBINE)',
                             'B01AF (INHIBITEURS DIRECTS DU FACTEUR Xa)',
                             'B01AX (AUTRES ANTITHROMBOTIQUES)'],
 'ANTICOAGULATIONPAR': ['B01AA (ANTIVITAMINES K)',
                        "B01AB (GROUPE DE L'HEPARINE)",
                        'B01AE (INHIBITEURS DIRECTS DE LA THROMBINE)',
                        'B01AF (INHIBITEURS DIRECTS DU FACTEUR Xa)',
                        'B01AX (AUTRES ANTITHROMBOTIQUES)'],
 'ANTICOAGULATIONPREVENTIVE': ['B01AA (ANTIVITAMINES K)',
                               "B01AB (GROUPE DE L'HEPARINE)",
                               'B01AE (INHIBITEURS DIRECTS DE LA THROMBINE)',
                               'B01AF (INHIBITEURS DIRECTS DU FACTEUR Xa)',
                               'B01AX (AUTRES ANTITHROMBOTIQUES)'],
 'ANTIDEPRESSEUR': ['N06A (ANTIDEPRESSEURS)'],
 'ANTIDIABETIQUE': ['A10B (ANTIDIABETIQUES, INSULINES EXCLUES)',
                    'A10A (INSULINES ET ANALOGUES)'],
 'ANTIDIABETIQUES': ['A10B (ANTIDIABETIQUES, INSULINES EXCLUES)',
                     'A10A (INSULINES ET ANALOGUES)'],
 'ANTIEMETIQUES': ['A04A (ANTIEMETIQUES ET ANTINAUSEEUX)'],
 'ANTIEPILEPTIQUES': ['N03A (ANTIEPILEPTIQUES)'],
 'ANTIFONGIQUES': ['D01A (ANTIFONGIQUES A USAGE TOPIQUE)',
                   'D01B (ANTIFONGIQUES A USAGE SYSTEMIQUE)'],
 'ANTIHISTAMINIQUE': ['R06A (ANTIHISTAMINIQUES A USAGE SYSTEMIQUE)'],
 'ANTIHISTAMINIQUES': ['R06A (ANTIHISTAMINIQUES A USAGE SYSTEMIQUE)'],
 'ANTIHYPERTENSEUR': ['C02K (AUTRES ANTIHYPERTENSEURS)',
                      'C02C (ADRENOLYTIQUES A ACTION PERIPHERIQUE)',
                      'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
                      'C02D (MEDICAMENTS AGISSANT SUR LE MUSCLE LISSE '
                      'ARTERIOLAIRE)',
                      'C02L (ANTIHYPERTENSEURS ET DIURETIQUES EN ASSOCIATION)'],
 'ANTIOBIOPROPHYLAXIE ANTIBIOTHERAPIE': ['J01C (BETALACTAMINES : PENICILLINES)',
                                         'J01X (AUTRES ANTIBACTERIENS)',
                                         'J01D (AUTRES BETALACTAMINES)',
                                         'J01M (QUINOLONES ANTIBACTERIENNES)',
                                         'J01F (MACROLIDES, LINCOSAMIDES  ET '
                                         'STREPTOGRAMINES)',
                                         'J01A (TETRACYCLINES)',
                                         'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                                         'J01G (AMINOSIDES ANTIBACTERIENS)',
                                         "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                                         'J01B (PHENICOLES)'],
 'ANTIOBIOTHERAPIE': ['J01C (BETALACTAMINES : PENICILLINES)',
                      'J01X (AUTRES ANTIBACTERIENS)',
                      'J01D (AUTRES BETALACTAMINES)',
                      'J01M (QUINOLONES ANTIBACTERIENNES)',
                      'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
                      'J01A (TETRACYCLINES)',
                      'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                      'J01G (AMINOSIDES ANTIBACTERIENS)',
                      "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                      'J01B (PHENICOLES)'],
 'ANTIPYRETIQUE': ['N02B (AUTRES ANALGESIQUES ET ANTIPYRETIQUES)'],
 'ANTITNF': ['L04AB (INHIBITEURS DU FACTEUR NECROSANT DES TUMEURS ALFA (TNF '
             'ALFA))'],
 'ANTITNFALPHA': ['L04AB (INHIBITEURS DU FACTEUR NECROSANT DES TUMEURS ALFA '
                  '(TNF ALFA))'],
 'ANTIVIRAUX': ['S01AD (ANTIVIRAUX)'],
 'ANTIVITAMINE K': ['B01AA (ANTIVITAMINES K)'],
 'ANXIOLYTIQUES': ['N05B (ANXIOLYTIQUES)'],
 'AOD': ['B01AE (INHIBITEURS DIRECTS DE LA THROMBINE)',
         'B01AF (INHIBITEURS DIRECTS DU FACTEUR Xa)'],
 'ARA2': ["C09C (ANTAGONISTES DE L'ANGIOTENSINE II)"],
 'ARV': ['S01AD (ANTIVIRAUX)', 'D06BB (ANTIVIRAUX)'],
 'ATB': ['J01C (BETALACTAMINES : PENICILLINES)',
         'J01X (AUTRES ANTIBACTERIENS)',
         'J01D (AUTRES BETALACTAMINES)',
         'J01M (QUINOLONES ANTIBACTERIENNES)',
         'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
         'J01A (TETRACYCLINES)',
         'J01E (SULFAMIDES ET TRIMETHOPRIME)',
         'J01G (AMINOSIDES ANTIBACTERIENS)',
         "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
         'J01B (PHENICOLES)'],
 'ATBTHERAPIE': ['J01C (BETALACTAMINES : PENICILLINES)',
                 'J01X (AUTRES ANTIBACTERIENS)',
                 'J01D (AUTRES BETALACTAMINES)',
                 'J01M (QUINOLONES ANTIBACTERIENNES)',
                 'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
                 'J01A (TETRACYCLINES)',
                 'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                 'J01G (AMINOSIDES ANTIBACTERIENS)',
                 "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                 'J01B (PHENICOLES)'],
 'AVK': ['B01AA (ANTIVITAMINES K)'],
 'B BLOQUANT': ['C07A (BETABLOQUANTS)'],
 'B BLOQUANTS': ['C07A (BETABLOQUANTS)'],
 'B LACTAMINE': ['J01C (BETALACTAMINES : PENICILLINES)'],
 'B LACTAMINES': ['J01D (AUTRES BETALACTAMINES)'],
 'B12': ['B03BA (VITAMINE B12 (CYANOCOBALAMINE ET DERIVES))'],
 'B2': ['R03CC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)'],
 'B2 MIMETIQUE': ['R03CC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)'],
 'B2 MIMETIQUES': ['R03CC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)'],
 'B6': ['A11DB (VITAMINE B1 EN ASSOCIATION A LA VITAMINE B6 ET,OU A LA '
        'VITAMINE B12)'],
 'BASAL': ["A10AE (INSULINES ET ANALOGUES POUR INJECTION D'ACTION LENTE)"],
 'BASAL BOLUS': ['A10A (INSULINES ET ANALOGUES)'],
 'BB': ['C07A (BETABLOQUANTS)'],
 'BBLOQUANT': ['C07A (BETABLOQUANTS)'],
 'BCG': ['L03AX03 (VACCIN BCG)'],
 'BENZODIAZEPINES': ['N05CD (DERIVES DE LA BENZODIAZEPINE)',
                     'N05CF (MEDICAMENTS RELIES AUX BENZODIAZEPINES)'],
 'BETA 2': ['R03AC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)',
            'R03CC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)'],
 'BETA 2 MIMETIQUES': ['R03AC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)',
                       'R03CC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)'],
 'BETA BLOQUANT': ['C07A (BETABLOQUANTS)'],
 'BETA BLOQUANTS': ['C07A (BETABLOQUANTS)'],
 'BETA ESTRADIOL': ['G03CA03 (ESTRADIOL)'],
 'BETA LACTAMINES': ['J01C (BETALACTAMINES : PENICILLINES)',
                     'J01D (AUTRES BETALACTAMINES)'],
 'BETA2': ['R03AC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)',
           'R03CC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)'],
 'BETA2 MIMETIQUE': ['R03AC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)',
                     'R03CC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)'],
 'BETA2 MIMETIQUES': ['R03AC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)',
                      'R03CC (AGONISTES SELECTIFS BETA 2 ADRENERGIQUES)'],
 'BETABLOQUANT': ['C07A (BETABLOQUANTS)'],
 'BETABLOQUANTS': ['C07A (BETABLOQUANTS)'],
 'BETABLOQUEUR': ['C07A (BETABLOQUANTS)'],
 'BETADINE DERMIQUE': ['S01AX18 (POVIDONE IODEE)'],
 'BETALACTAMINES': ['J01C (BETALACTAMINES : PENICILLINES)',
                    'J01D (AUTRES BETALACTAMINES)'],
 'BI AGREGATION': ['B01AC06 (ACETYLSALICYLIQUE ACIDE)',
                   'B01AC04 (CLOPIDOGREL)',
                   'B01AC24 (TICAGRELOR)',
                   'B01AC22 (PRASUGREL)'],
 'BI ANTI AGREGATION': ['B01AC06 (ACETYLSALICYLIQUE ACIDE)',
                        'B01AC04 (CLOPIDOGREL)',
                        'B01AC24 (TICAGRELOR)',
                        'B01AC22 (PRASUGREL)'],
 'BI ANTIAGREGATION': ['B01AC06 (ACETYLSALICYLIQUE ACIDE)',
                       'B01AC04 (CLOPIDOGREL)',
                       'B01AC24 (TICAGRELOR)',
                       'B01AC22 (PRASUGREL)'],
 'BI ANTIAGREGATION PLAQUETTAIRE': ['B01AC06 (ACETYLSALICYLIQUE ACIDE)',
                                    'B01AC04 (CLOPIDOGREL)',
                                    'B01AC24 (TICAGRELOR)',
                                    'B01AC22 (PRASUGREL)'],
 'BI ANTIBIOTHERAPIE': ['J01C (BETALACTAMINES : PENICILLINES)',
                        'J01X (AUTRES ANTIBACTERIENS)',
                        'J01D (AUTRES BETALACTAMINES)',
                        'J01M (QUINOLONES ANTIBACTERIENNES)',
                        'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
                        'J01A (TETRACYCLINES)',
                        'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                        'J01G (AMINOSIDES ANTIBACTERIENS)',
                        "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                        'J01B (PHENICOLES)'],
 'BIANTIBIOTHERAPIE': ['J01C (BETALACTAMINES : PENICILLINES)',
                       'J01X (AUTRES ANTIBACTERIENS)',
                       'J01D (AUTRES BETALACTAMINES)',
                       'J01M (QUINOLONES ANTIBACTERIENNES)',
                       'J01F (MACROLIDES, LINCOSAMIDES  ET STREPTOGRAMINES)',
                       'J01A (TETRACYCLINES)',
                       'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                       'J01G (AMINOSIDES ANTIBACTERIENS)',
                       "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                       'J01B (PHENICOLES)'],
 'BICARBONATES': ['B05XA02 (SODIUM BICARBONATE)'],
 'BIOTINE': ['A11HA05 (BIOTINE)'],
 'BIPHOSPHONATE': ['M05BA (DIPHOSPHONATES)'],
 'BIPHOSPHONATES': ['M05BA (DIPHOSPHONATES)'],
 'BISPHOSPHONATES': ['M05BA (DIPHOSPHONATES)'],
 'BRONCHO DILATATEURS': ['R03A (ADRENERGIQUES POUR INHALATION)',
                         'R03C (ADRENERGIQUES A USAGE SYSTEMIQUE)',
                         'R03D (AUTRES MEDICAMENTS SYSTEMIQUES POUR LES '
                         'SYNDROMES OBSTRUCTIFS DES VOIES AERIENNES)',
                         'R03B (AUTRES MEDICAMENTS POUR LES SYNDROMES '
                         'OBSTRUCTIFS DES VOIES AERIENNES, PAR INHALATION)'],
 'BRONCHODILATATEUR': ['R03A (ADRENERGIQUES POUR INHALATION)',
                       'R03C (ADRENERGIQUES A USAGE SYSTEMIQUE)',
                       'R03D (AUTRES MEDICAMENTS SYSTEMIQUES POUR LES '
                       'SYNDROMES OBSTRUCTIFS DES VOIES AERIENNES)',
                       'R03B (AUTRES MEDICAMENTS POUR LES SYNDROMES '
                       'OBSTRUCTIFS DES VOIES AERIENNES, PAR INHALATION)'],
 'BRONCHODILATATEURS': ['R03A (ADRENERGIQUES POUR INHALATION)',
                        'R03C (ADRENERGIQUES A USAGE SYSTEMIQUE)',
                        'R03D (AUTRES MEDICAMENTS SYSTEMIQUES POUR LES '
                        'SYNDROMES OBSTRUCTIFS DES VOIES AERIENNES)',
                        'R03B (AUTRES MEDICAMENTS POUR LES SYNDROMES '
                        'OBSTRUCTIFS DES VOIES AERIENNES, PAR INHALATION)'],
 'BZD': ['N05CD (DERIVES DE LA BENZODIAZEPINE)',
         'N05CF (MEDICAMENTS RELIES AUX BENZODIAZEPINES)'],
 'C3G': ['J01DD (CEPHALOSPORINES DE TROISIEME GENERATION)'],
 'CALCIQUE': ['C08C (INHIBITEURS CALCIQUES SELECTIFS A EFFET VASCULAIRE '
              'PREDOMINANT)',
              'C08D (INHIBITEURS CALCIQUES SELECTIFS A EFFETS CARDIAQUES '
              'DIRECTS)',
              'C08G (INHIBITEURS CALCIQUES ET DIURETIQUES)'],
 'CALCIUM': ['A12A (CALCIUM)'],
 'CATECHOLAMINES': ['C01CA (ADRENERGIQUES ET DOPAMINERGIQUES)'],
 'CHIMIO': ["L01C (ALCALOIDES VEGETAUX ET AUTRES MEDICAMENTS D'ORIGINE "
            'NATURELLE)',
            'L01X (AUTRES ANTINEOPLASIQUES)',
            'L01A (AGENTS ALKYLANTS)',
            'L01B (ANTIMETABOLITES)',
            'L01D (ANTIBIOTIQUES CYTOTOXIQUES ET APPARENTES)'],
 'CHIMIO EMBOLISATION': ['L01C (ALCALOIDES VEGETAUX ET AUTRES MEDICAMENTS '
                         "D'ORIGINE NATURELLE)",
                         'L01X (AUTRES ANTINEOPLASIQUES)',
                         'L01A (AGENTS ALKYLANTS)',
                         'L01B (ANTIMETABOLITES)',
                         'L01D (ANTIBIOTIQUES CYTOTOXIQUES ET APPARENTES)'],
 'CHIMIO RADIOTHERAPIE': ['L01C (ALCALOIDES VEGETAUX ET AUTRES MEDICAMENTS '
                          "D'ORIGINE NATURELLE)",
                          'L01X (AUTRES ANTINEOPLASIQUES)',
                          'L01A (AGENTS ALKYLANTS)',
                          'L01B (ANTIMETABOLITES)',
                          'L01D (ANTIBIOTIQUES CYTOTOXIQUES ET APPARENTES)'],
 'CHIMIOEMBOLISATION': ['L01C (ALCALOIDES VEGETAUX ET AUTRES MEDICAMENTS '
                        "D'ORIGINE NATURELLE)",
                        'L01X (AUTRES ANTINEOPLASIQUES)',
                        'L01A (AGENTS ALKYLANTS)',
                        'L01B (ANTIMETABOLITES)',
                        'L01D (ANTIBIOTIQUES CYTOTOXIQUES ET APPARENTES)'],
 'CHIMIOTHERAPIE': ["L01C (ALCALOIDES VEGETAUX ET AUTRES MEDICAMENTS D'ORIGINE "
                    'NATURELLE)',
                    'L01X (AUTRES ANTINEOPLASIQUES)',
                    'L01A (AGENTS ALKYLANTS)',
                    'L01B (ANTIMETABOLITES)',
                    'L01D (ANTIBIOTIQUES CYTOTOXIQUES ET APPARENTES)'],
 'CHIMIOTHERAPIE ADJUVANTE': ['L01C (ALCALOIDES VEGETAUX ET AUTRES MEDICAMENTS '
                              "D'ORIGINE NATURELLE)",
                              'L01X (AUTRES ANTINEOPLASIQUES)',
                              'L01A (AGENTS ALKYLANTS)',
                              'L01B (ANTIMETABOLITES)',
                              'L01D (ANTIBIOTIQUES CYTOTOXIQUES ET '
                              'APPARENTES)'],
 'CHIMIOTHERAPIES': ['L01C (ALCALOIDES VEGETAUX ET AUTRES MEDICAMENTS '
                     "D'ORIGINE NATURELLE)",
                     'L01X (AUTRES ANTINEOPLASIQUES)',
                     'L01A (AGENTS ALKYLANTS)',
                     'L01B (ANTIMETABOLITES)',
                     'L01D (ANTIBIOTIQUES CYTOTOXIQUES ET APPARENTES)'],
 'CNO': ['V06C (PREPARATIONS PEDIATRIQUES)',
         'V06D (AUTRES NUTRIMENTS)',
         'V06D (AUTRES NUTRIMENTS)'],
 'COLLYRE ANTIBIOTIQUES': ['S01AA (ANTIBIOTIQUES)'],
 'COMPLEMENT ALIMENTAIRES': ['V06C (PREPARATIONS PEDIATRIQUES)',
                             'V06D (AUTRES NUTRIMENTS)',
                             'V06D (AUTRES NUTRIMENTS)'],
 'COMPLEMENT NUTRITIONNELS': ['V06C (PREPARATIONS PEDIATRIQUES)',
                              'V06D (AUTRES NUTRIMENTS)',
                              'V06D (AUTRES NUTRIMENTS)'],
 'CONTRACEPTION OESTROPROGESTATIVE': ['G03AA (PROGESTATIFS ET ESTROGENES EN '
                                      'ASSOCIATION FIXE)',
                                      'G03AB (PROGESTATIFS ET ESTROGENES POUR '
                                      'ADMINISTRATION SEQUENTIELLE)'],
 'CORTICIOTHERAPIE': ['H02A (CORTICOIDES A USAGE SYSTEMIQUE NON ASSOCIES)'],
 'CORTICO': ['H02A (CORTICOIDES A USAGE SYSTEMIQUE NON ASSOCIES)'],
 'CORTICOIDE': ['H02A (CORTICOIDES A USAGE SYSTEMIQUE NON ASSOCIES)'],
 'CORTICOIDES': ['H02A (CORTICOIDES A USAGE SYSTEMIQUE NON ASSOCIES)'],
 'CORTICOSTEROIDES': ['H02A (CORTICOIDES A USAGE SYSTEMIQUE NON ASSOCIES)'],
 'CORTICOTHERAPIE': ['H02A (CORTICOIDES A USAGE SYSTEMIQUE NON ASSOCIES)'],
 'CORTICOTHRAPIE': ['H02A (CORTICOIDES A USAGE SYSTEMIQUE NON ASSOCIES)'],
 'CORTICOTTT': ['H02A (CORTICOIDES A USAGE SYSTEMIQUE NON ASSOCIES)'],
 'CORTISONIQUE': ['H02A (CORTICOIDES A USAGE SYSTEMIQUE NON ASSOCIES)'],
 'COUVERTURE ANTIBIOTIQUE': ['J01C (BETALACTAMINES : PENICILLINES)',
                             'J01X (AUTRES ANTIBACTERIENS)',
                             'J01D (AUTRES BETALACTAMINES)',
                             'J01M (QUINOLONES ANTIBACTERIENNES)',
                             'J01F (MACROLIDES, LINCOSAMIDES  ET '
                             'STREPTOGRAMINES)',
                             'J01A (TETRACYCLINES)',
                             'J01E (SULFAMIDES ET TRIMETHOPRIME)',
                             'J01G (AMINOSIDES ANTIBACTERIENS)',
                             "J01R (ASSOCIATIONS D'ANTIBACTERIENS)",
                             'J01B (PHENICOLES)'],
 'CRISTALLOIDES': ['B05BB01 (ELECTROLYTES)'],
 'DEPLETION': ['C03B (DIURETIQUES LOW-CEILING, THIAZIDIQUES EXCLUS)',
               "C03C (DIURETIQUES DE L'ANSE)",
               'C03E (DIURETIQUES ET EPARGNEURS POTASSIQUES EN ASSOCIATION)',
               'C03D (DIURETIQUES EPARGNEURS POTASSIQUES)',
               'C03X (AUTRES DIURETIQUES)',
               'C03A (DIURETIQUES LOW-CEILING, THIAZIDIQUES)'],
 'DEPLETION HYDRO SODEE': ['C03B (DIURETIQUES LOW-CEILING, THIAZIDIQUES '
                           'EXCLUS)',
                           "C03C (DIURETIQUES DE L'ANSE)",
                           'C03E (DIURETIQUES ET EPARGNEURS POTASSIQUES EN '
                           'ASSOCIATION)',
                           'C03D (DIURETIQUES EPARGNEURS POTASSIQUES)',
                           'C03X (AUTRES DIURETIQUES)',
                           'C03A (DIURETIQUES LOW-CEILING, THIAZIDIQUES)'],
 'DEPLETION HYDROSODEE': ['C03B (DIURETIQUES LOW-CEILING, THIAZIDIQUES EXCLUS)',
                          "C03C (DIURETIQUES DE L'ANSE)",
                          'C03E (DIURETIQUES ET EPARGNEURS POTASSIQUES EN '
                          'ASSOCIATION)',
                          'C03D (DIURETIQUES EPARGNEURS POTASSIQUES)',
                          'C03X (AUTRES DIURETIQUES)',
                          'C03A (DIURETIQUES LOW-CEILING, THIAZIDIQUES)'],
 'DERMOCORTICOIDES': ['D07A (CORTICOIDES NON ASSOCIES)'],
 'DIURETIQUE': ['C03B (DIURETIQUES LOW-CEILING, THIAZIDIQUES EXCLUS)',
                "C03C (DIURETIQUES DE L'ANSE)",
                'C03E (DIURETIQUES ET EPARGNEURS POTASSIQUES EN ASSOCIATION)',
                'C03D (DIURETIQUES EPARGNEURS POTASSIQUES)',
                'C03X (AUTRES DIURETIQUES)',
                'C03A (DIURETIQUES LOW-CEILING, THIAZIDIQUES)'],
 'DIURETIQUE THIAZIDIQUE': ['C03A (DIURETIQUES LOW-CEILING, THIAZIDIQUES)'],
 'DIURETIQUES': ['C03B (DIURETIQUES LOW-CEILING, THIAZIDIQUES EXCLUS)',
                 "C03C (DIURETIQUES DE L'ANSE)",
                 'C03E (DIURETIQUES ET EPARGNEURS POTASSIQUES EN ASSOCIATION)',
                 'C03D (DIURETIQUES EPARGNEURS POTASSIQUES)',
                 'C03X (AUTRES DIURETIQUES)',
                 'C03A (DIURETIQUES LOW-CEILING, THIAZIDIQUES)'],
 'EPILEPTIQUE': ['N03A (ANTIEPILEPTIQUES)'],
 'EPO': ['B03XA01 (ERYTHROPOIETINE)'],
 'FER': ['B03A (PREPARATIONS MARTIALES)'],
 'FOLATES': ['B03BB01 (FOLIQUE ACIDE)'],
 'G CSF': ['L03AA02 (FILGRASTIM)'],
 'GAMMAGLOBULINES': ['J06B (IMMUNOGLOBULINES)'],
 'HBPM': ['B01AB04 (DALTEPARINE)',
          'B01AB06 (NADROPARINE)',
          'B01AB05 (ENOXAPARINE)',
          'B01AB10 (TINZAPARINE)'],
 'HEMISUCCINATE': ['H02AB (GLUCOCORTICOIDES)'],
 'HEPARINE': ['B01AB01 (HEPARINE)'],
 'HEPARINOTHERAPIE': ["B01AB (GROUPE DE L'HEPARINE)"],
 'HNF': ['B01AB01 (HEPARINE)'],
 'HSHC': ['H02AB (GLUCOCORTICOIDES)'],
 'HYPNOTIQUES': ['N05C (HYPNOTIQUES ET SEDATIFS)'],
 'IEC': ["C09A (INHIBITEURS DE L'ENZYME DE CONVERSION (IEC) NON ASSOCIES)"],
 'IG': ['J06B (IMMUNOGLOBULINES)'],
 'IGG': ['J06B (IMMUNOGLOBULINES)'],
 'IGIV': ['J06B (IMMUNOGLOBULINES)'],
 'IMMUNO SUPPRESSEUR': ['L04A (IMMUNOSUPPRESSEURS)'],
 'IMMUNO SUPPRESSEURS': ['L04A (IMMUNOSUPPRESSEURS)'],
 'IMMUNOGLOBULINE': ['J06B (IMMUNOGLOBULINES)'],
 'IMMUNOGLOBULINE POLYVALENTES': ['J06BA (IMMUNOGLOBULINES HUMAINES '
                                  'POLYVALENTES)'],
 'IMMUNOGLOBULINES': ['J06B (IMMUNOGLOBULINES)'],
 'IMMUNOSUPPRESSEUR': ['L04A (IMMUNOSUPPRESSEURS)'],
 'IMMUNOSUPPRESSEURS': ['L04A (IMMUNOSUPPRESSEURS)'],
 'IMMUNOSUPPRESSION': ['L04A (IMMUNOSUPPRESSEURS)'],
 'IMMUNOSUPRESSEUR': ['L04A (IMMUNOSUPPRESSEURS)'],
 'IMMUNOSUPRESSEURS': ['L04A (IMMUNOSUPPRESSEURS)'],
 'IMMUNOTHERAPIE': ['J06B (IMMUNOGLOBULINES)'],
 'IMUNOTHERAPIE': ['J06B (IMMUNOGLOBULINES)'],
 'INFLIXIMAB': ['L04AB02 (INFLIXIMAB)'],
 'INHIBITEUR CALCIQUE': ['C08C (INHIBITEURS CALCIQUES SELECTIFS A EFFET '
                         'VASCULAIRE PREDOMINANT)',
                         'C08D (INHIBITEURS CALCIQUES SELECTIFS A EFFETS '
                         'CARDIAQUES DIRECTS)',
                         'C08G (INHIBITEURS CALCIQUES ET DIURETIQUES)'],
 'INHIBITEUR CALCIQUES': ['C08C (INHIBITEURS CALCIQUES SELECTIFS A EFFET '
                          'VASCULAIRE PREDOMINANT)',
                          'C08D (INHIBITEURS CALCIQUES SELECTIFS A EFFETS '
                          'CARDIAQUES DIRECTS)',
                          'C08G (INHIBITEURS CALCIQUES ET DIURETIQUES)'],
 'INOTROPES': ['C01C (STIMULANTS CARDIAQUES, GLUCOSIDES CARDIOTONIQUES '
               'EXCLUS)'],
 'INSULINE': ['A10A (INSULINES ET ANALOGUES)'],
 'INSULINE GLUCOSE': ['A10A (INSULINES ET ANALOGUES)'],
 'INSULINE HUMAINE': ['A10AD01 (INSULINE HUMAINE)',
                      'A10AC01 (INSULINE HUMAINE)',
                      'A10AB01 (INSULINE HUMAINE)'],
 'INSULINE LENTE': ['A10A (INSULINES ET ANALOGUES)'],
 'INSULINE RAPIDE': ['A10A (INSULINES ET ANALOGUES)'],
 'INSULINES': ['A10A (INSULINES ET ANALOGUES)'],
 'INSULINOREQUERANCE': ['A10A (INSULINES ET ANALOGUES)'],
 'INSULINOTHERAPIE': ['A10A (INSULINES ET ANALOGUES)'],
 'IPP': ['A02BC (INHIBITEURS DE LA POMPE A PROTONS)'],
 'ITK': ['L03AC (INTERLEUKINES)'],
 'LAXATIF': ['A06A (MEDICAMENTS POUR LA CONSTIPATION)'],
 'LAXATIFS': ['A06A (MEDICAMENTS POUR LA CONSTIPATION)'],
 'MACROLIDES': ['J01FA (MACROLIDES)'],
 'MORPHINE': ['N02AA01 (MORPHINE)'],
 'MORPHINIQUE': ['N02AA01 (MORPHINE)'],
 'MORPHINIQUES': ['N02AA01 (MORPHINE)'],
 'NEUROLEPTIQUE': ['N05A (ANTIPSYCHOTIQUES)'],
 'NEUROLEPTIQUES': ['N05A (ANTIPSYCHOTIQUES)'],
 'NUTRITION PARENTERALE': ['B05BA (SOLUTIONS POUR NUTRITION PARENTERALE)'],
 'O2': ['V03AN01 (OXYGENE)'],
 'O2 LUNETTES': ['V03AN01 (OXYGENE)'],
 'OPIACES': ['N02A (OPIOIDES)'],
 'OXYGENE': ['V03AN01 (OXYGENE)'],
 'OXYGENOTHERAPIE': ['V03AN01 (OXYGENE)'],
 'PANSEMENT GRAS': ['D02AC (PARAFFINE ET PRODUITS GRAS)'],
 'PCA': ['N02AA01 (MORPHINE)'],
 'PEG': ['A06AD15 (MACROGOL)'],
 'PHOSPHATE DISODIQUE': ['A06AG (LAVEMENTS)'],
 'PILULE CONTRACEPTIVE': ['G03A (CONTRACEPTIFS HORMONAUX A USAGE SYSTEMIQUE)'],
 'POLYCHIMIOTHERAPIE': ['L01C (ALCALOIDES VEGETAUX ET AUTRES MEDICAMENTS '
                        "D'ORIGINE NATURELLE)",
                        'L01X (AUTRES ANTINEOPLASIQUES)',
                        'L01A (AGENTS ALKYLANTS)',
                        'L01B (ANTIMETABOLITES)',
                        'L01D (ANTIBIOTIQUES CYTOTOXIQUES ET APPARENTES)'],
 'PRODUIT DE CONTRASTE': ['V08A (PRODUITS DE CONTRASTE IODES)'],
 'PRODUIT DE CONTRASTE IODE': ['V08A (PRODUITS DE CONTRASTE IODES)'],
 'PRODUIT DE CONTRASTE IODES': ['V08A (PRODUITS DE CONTRASTE IODES)'],
 'PROPHYLAXIE ANTI THROMBOTIQUE': ['B01A (ANTITHROMBOTIQUES)'],
 'PSYCHOTROPES': ['N05C (HYPNOTIQUES ET SEDATIFS)',
                  'N05A (ANTIPSYCHOTIQUES)',
                  'N05B (ANXIOLYTIQUES)'],
 'QUADRITHERAPIE ANTI HYPERTENSIVE': ['C02K (AUTRES ANTIHYPERTENSEURS)',
                                      'C02C (ADRENOLYTIQUES A ACTION '
                                      'PERIPHERIQUE)',
                                      'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
                                      'C02D (MEDICAMENTS AGISSANT SUR LE '
                                      'MUSCLE LISSE ARTERIOLAIRE)',
                                      'C02L (ANTIHYPERTENSEURS ET DIURETIQUES '
                                      'EN ASSOCIATION)',
                                      'C03B (DIURETIQUES LOW-CEILING, '
                                      'THIAZIDIQUES EXCLUS)',
                                      "C03C (DIURETIQUES DE L'ANSE)",
                                      'C03E (DIURETIQUES ET EPARGNEURS '
                                      'POTASSIQUES EN ASSOCIATION)',
                                      'C03D (DIURETIQUES EPARGNEURS '
                                      'POTASSIQUES)',
                                      'C03X (AUTRES DIURETIQUES)',
                                      'C03A (DIURETIQUES LOW-CEILING, '
                                      'THIAZIDIQUES)',
                                      'C07A (BETABLOQUANTS)',
                                      'C07B (BETABLOQUANTS ET THIAZIDIQUES)',
                                      'C07D (BETABLOQUANTS, THIAZIDIQUES ET '
                                      'AUTRES DIURETIQUES)',
                                      'C07F (BETABLOQUANTS ET AUTRES '
                                      'ANTIHYPERTENSEURS)',
                                      'C07C (BETABLOQUANTS ET AUTRES '
                                      'DIURETIQUES)',
                                      'C08C (INHIBITEURS CALCIQUES SELECTIFS A '
                                      'EFFET VASCULAIRE PREDOMINANT)',
                                      'C08D (INHIBITEURS CALCIQUES SELECTIFS A '
                                      'EFFETS CARDIAQUES DIRECTS)',
                                      'C08G (INHIBITEURS CALCIQUES ET '
                                      'DIURETIQUES)',
                                      "C09B (INHIBITEURS DE L'ENZYME DE "
                                      'CONVERSION (IEC) EN ASSOCIATION)',
                                      "C09A (INHIBITEURS DE L'ENZYME DE "
                                      'CONVERSION (IEC) NON ASSOCIES)',
                                      "C09C (ANTAGONISTES DE L'ANGIOTENSINE "
                                      'II)',
                                      "C09D (ANTAGONISTES DE L'ANGIOTENSINE II "
                                      'EN ASSOCIATION)',
                                      'C09X (AUTRES MEDICAMENTS AGISSANT SUR '
                                      'LE SYSTEME RENINE-ANGIOTENSINE)'],
 'QUADRITHERAPIE ANTITUBERCULEUSE': ['J04A (ANTITUBERCULEUX)',
                                     'J04B (ANTILEPREUX)'],
 'RADIO CHIMIOTHERAPIE': ['D06BX (AUTRES CHIMIOTHERAPIES)'],
 'RECHARGE POTASSIQUE': ['A12B (POTASSIUM)'],
 'SEDATION': ['N05C (HYPNOTIQUES ET SEDATIFS)'],
 'SEDATIONS': ['N05C (HYPNOTIQUES ET SEDATIFS)'],
 'SERUM PHYSIOLOGIQUE': ['B05BB01 (ELECTROLYTES)'],
 'SOMNIFERES': ['N05C (HYPNOTIQUES ET SEDATIFS)'],
 'STATINE': ["C10AA (INHIBITEURS DE L'HMG-COA REDUCTASE)"],
 'STATINES': ["C10AA (INHIBITEURS DE L'HMG-COA REDUCTASE)"],
 'SULFATE FERREUX': ['B03AD03 (SULFATE FERREUX)', 'B03AA07 (SULFATE FERREUX)'],
 'SUPPLEMENTATION MARTIALE': ['B03X (AUTRES PREPARATIONS ANTIANEMIQUES)',
                              'B03A (PREPARATIONS MARTIALES)',
                              'B03B (VITAMINE B12 ET ACIDE FOLIQUE)'],
 'SUPPLEMENTATION POTASSIQUE': ['A12B (POTASSIUM)'],
 'SUPPLEMENTATION VITAMINIQUE': ['A11A (POLYVITAMINES EN ASSOCIATION)'],
 'SUPPLEMENTATION VITAMINO CALCIQUE': ['A11A (POLYVITAMINES EN ASSOCIATION)'],
 'SUPPORT CATECHOLAMINERGIQUE': ['C01CA (ADRENERGIQUES ET DOPAMINERGIQUES)'],
 'SUPPORT TRANSFUSIONNEL': ['B05A (SANG ET DERIVES)'],
 'SUPPORT VASOPRESSEUR': ['C01CA (ADRENERGIQUES ET DOPAMINERGIQUES)'],
 'TITRATION MORPHINE': ['N02AA01 (MORPHINE)'],
 'TITRATION MORPHINIQUE': ['N02AA01 (MORPHINE)'],
 'TRAITEMENT ANTI ARYTHMIQUE': ['C01B (ANTIARYTHMIQUES, CLASSE I ET III)'],
 'TRAITEMENT ANTI COAGULANT': ['B01A (ANTITHROMBOTIQUES)'],
 'TRAITEMENT ANTI DEPRESSEUR': ['N06A (ANTIDEPRESSEURS)'],
 'TRAITEMENT ANTI DIABETIQUE': ['A10B (ANTIDIABETIQUES, INSULINES EXCLUES)',
                                'A10A (INSULINES ET ANALOGUES)'],
 'TRAITEMENT ANTI EMETIQUE': ['A04A (ANTIEMETIQUES ET ANTINAUSEEUX)'],
 'TRAITEMENT ANTI EMETIQUES': ['A04A (ANTIEMETIQUES ET ANTINAUSEEUX)'],
 'TRAITEMENT ANTI EPILEPTIQUE': ['N03A (ANTIEPILEPTIQUES)'],
 'TRAITEMENT ANTI FONGIQUE': ['D01A (ANTIFONGIQUES A USAGE TOPIQUE)',
                              'D01B (ANTIFONGIQUES A USAGE SYSTEMIQUE)'],
 'TRAITEMENT ANTI HTA': ['C02K (AUTRES ANTIHYPERTENSEURS)',
                         'C02C (ADRENOLYTIQUES A ACTION PERIPHERIQUE)',
                         'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
                         'C02D (MEDICAMENTS AGISSANT SUR LE MUSCLE LISSE '
                         'ARTERIOLAIRE)',
                         'C02L (ANTIHYPERTENSEURS ET DIURETIQUES EN '
                         'ASSOCIATION)'],
 'TRAITEMENT ANTI HYPERTENSEUR': ['C02K (AUTRES ANTIHYPERTENSEURS)',
                                  'C02C (ADRENOLYTIQUES A ACTION PERIPHERIQUE)',
                                  'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
                                  'C02D (MEDICAMENTS AGISSANT SUR LE MUSCLE '
                                  'LISSE ARTERIOLAIRE)',
                                  'C02L (ANTIHYPERTENSEURS ET DIURETIQUES EN '
                                  'ASSOCIATION)'],
 'TRAITEMENT ANTI HYPERTENSEURS': ['C02K (AUTRES ANTIHYPERTENSEURS)',
                                   'C02C (ADRENOLYTIQUES A ACTION '
                                   'PERIPHERIQUE)',
                                   'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
                                   'C02D (MEDICAMENTS AGISSANT SUR LE MUSCLE '
                                   'LISSE ARTERIOLAIRE)',
                                   'C02L (ANTIHYPERTENSEURS ET DIURETIQUES EN '
                                   'ASSOCIATION)'],
 'TRAITEMENT ANTI INFLAMMATOIRE': ['S01B (ANTIINFLAMMATOIRES)',
                                   'A07E (ANTIINFLAMMATOIRES INTESTINAUX)'],
 'TRAITEMENT ANTI OSTEOPOROTIQUE': ['M05B (MEDICAMENTS AGISSANT SUR LA '
                                    'STRUCTURE OSSEUSE ET SUR LA '
                                    'MINERALISATION)'],
 'TRAITEMENT ANTI REFLUX': ["A02B (MEDICAMENTS POUR L'ULCERE GASTRO-DUODENAL "
                            'ET LE REFLUX GASTRO-OESOPHAGIEN (RGO))',
                            'A02A (ANTIACIDES)',
                            'A02X (AUTRES MEDICAMENTS POUR LES TROUBLES DE '
                            "L'ACIDITE)"],
 'TRAITEMENT ANTI REJET': ['L04A (IMMUNOSUPPRESSEURS)',
                           'H02A (CORTICOIDES A USAGE SYSTEMIQUE NON '
                           'ASSOCIES)'],
 'TRAITEMENT ANTI TUBERCULEUX': ['J04A (ANTITUBERCULEUX)'],
 'TRAITEMENT ANTI VIRAL': ['D06BB (ANTIVIRAUX)',
                           'J05A (ANTIVIRAUX A ACTION DIRECTE)',
                           'S01AD (ANTIVIRAUX)'],
 'TRAITEMENT ANTIBIOTIQUE': ['J04AB (ANTIBIOTIQUES)',
                             'S01AA (ANTIBIOTIQUES)',
                             'J02AA (ANTIBIOTIQUES)',
                             'A07AA (ANTIBIOTIQUES)',
                             'G01AA (ANTIBIOTIQUES)'],
 'TRAITEMENT ANTIBIOTIQUES': ['J04AB (ANTIBIOTIQUES)',
                              'S01AA (ANTIBIOTIQUES)',
                              'J02AA (ANTIBIOTIQUES)',
                              'A07AA (ANTIBIOTIQUES)',
                              'G01AA (ANTIBIOTIQUES)'],
 'TRAITEMENT ANTICHOLINERGIQUE': ['N04A (ANTICHOLINERGIQUES)'],
 'TRAITEMENT ANTICO': ['B01A (ANTITHROMBOTIQUES)'],
 'TRAITEMENT ANTICOAGULANT': ['B01A (ANTITHROMBOTIQUES)'],
 'TRAITEMENT ANTICOAGULANTS': ['B01A (ANTITHROMBOTIQUES)'],
 'TRAITEMENT ANTIDEPRESSEUR': ['N06A (ANTIDEPRESSEURS)'],
 'TRAITEMENT ANTIDIABETIQUE': ['A10B (ANTIDIABETIQUES, INSULINES EXCLUES)',
                               'A10A (INSULINES ET ANALOGUES)'],
 'TRAITEMENT ANTIEPILEPTIQUE': ['N03A (ANTIEPILEPTIQUES)'],
 'TRAITEMENT ANTIFONGIQUE': ['D01A (ANTIFONGIQUES A USAGE TOPIQUE)',
                             'D01B (ANTIFONGIQUES A USAGE SYSTEMIQUE)'],
 'TRAITEMENT ANTIHYPERTENSEUR': ['C02K (AUTRES ANTIHYPERTENSEURS)',
                                 'C02C (ADRENOLYTIQUES A ACTION PERIPHERIQUE)',
                                 'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
                                 'C02D (MEDICAMENTS AGISSANT SUR LE MUSCLE '
                                 'LISSE ARTERIOLAIRE)',
                                 'C02L (ANTIHYPERTENSEURS ET DIURETIQUES EN '
                                 'ASSOCIATION)'],
 'TRAITEMENT ANTIHYPERTENSEURS': ['C02K (AUTRES ANTIHYPERTENSEURS)',
                                  'C02C (ADRENOLYTIQUES A ACTION PERIPHERIQUE)',
                                  'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
                                  'C02D (MEDICAMENTS AGISSANT SUR LE MUSCLE '
                                  'LISSE ARTERIOLAIRE)',
                                  'C02L (ANTIHYPERTENSEURS ET DIURETIQUES EN '
                                  'ASSOCIATION)'],
 'TRAITEMENT ANTITUBERCULEUX': ['J04A (ANTITUBERCULEUX)'],
 'TRAITEMENT ANTIVIRAL': ['D06BB (ANTIVIRAUX)',
                          'J05A (ANTIVIRAUX A ACTION DIRECTE)',
                          'S01AD (ANTIVIRAUX)'],
 'TRAITEMENT ANXIOLYTIQUE': ['N05B (ANXIOLYTIQUES)'],
 'TRAITEMENT BETABLOQUANT': ['C07A (BETABLOQUANTS)',
                             'C07B (BETABLOQUANTS ET THIAZIDIQUES)',
                             'C07D (BETABLOQUANTS, THIAZIDIQUES ET AUTRES '
                             'DIURETIQUES)',
                             'C07F (BETABLOQUANTS ET AUTRES ANTIHYPERTENSEURS)',
                             'C07C (BETABLOQUANTS ET AUTRES DIURETIQUES)'],
 'TRAITEMENT BRADYCARDISANT': ['C07A (BETABLOQUANTS)',
                               'C07B (BETABLOQUANTS ET THIAZIDIQUES)',
                               'C07D (BETABLOQUANTS, THIAZIDIQUES ET AUTRES '
                               'DIURETIQUES)',
                               'C07F (BETABLOQUANTS ET AUTRES '
                               'ANTIHYPERTENSEURS)',
                               'C07C (BETABLOQUANTS ET AUTRES DIURETIQUES)',
                               'C08C (INHIBITEURS CALCIQUES SELECTIFS A EFFET '
                               'VASCULAIRE PREDOMINANT)',
                               'C08D (INHIBITEURS CALCIQUES SELECTIFS A EFFETS '
                               'CARDIAQUES DIRECTS)',
                               'C08G (INHIBITEURS CALCIQUES ET DIURETIQUES)'],
 'TRAITEMENT DEPLETIF': ['C03B (DIURETIQUES LOW-CEILING, THIAZIDIQUES EXCLUS)',
                         "C03C (DIURETIQUES DE L'ANSE)",
                         'C03E (DIURETIQUES ET EPARGNEURS POTASSIQUES EN '
                         'ASSOCIATION)',
                         'C03D (DIURETIQUES EPARGNEURS POTASSIQUES)',
                         'C03X (AUTRES DIURETIQUES)',
                         'C03A (DIURETIQUES LOW-CEILING, THIAZIDIQUES)'],
 'TRAITEMENT DIURETIQUE': ['C03B (DIURETIQUES LOW-CEILING, THIAZIDIQUES '
                           'EXCLUS)',
                           "C03C (DIURETIQUES DE L'ANSE)",
                           'C03E (DIURETIQUES ET EPARGNEURS POTASSIQUES EN '
                           'ASSOCIATION)',
                           'C03D (DIURETIQUES EPARGNEURS POTASSIQUES)',
                           'C03X (AUTRES DIURETIQUES)',
                           'C03A (DIURETIQUES LOW-CEILING, THIAZIDIQUES)'],
 'TRAITEMENT HYPOTENSEUR': ['C02K (AUTRES ANTIHYPERTENSEURS)',
                            'C02C (ADRENOLYTIQUES A ACTION PERIPHERIQUE)',
                            'C02A (ADRENOLYTIQUES A ACTION CENTRALE)',
                            'C02D (MEDICAMENTS AGISSANT SUR LE MUSCLE LISSE '
                            'ARTERIOLAIRE)',
                            'C02L (ANTIHYPERTENSEURS ET DIURETIQUES EN '
                            'ASSOCIATION)'],
 'TRAITEMENT IMMUNOSUPPRESSEUR': ['L04A (IMMUNOSUPPRESSEURS)'],
 'TRAITEMENT IMMUNOSUPPRESSEURS': ['L04A (IMMUNOSUPPRESSEURS)'],
 'TRAITEMENT INOTROPE': ['C01C (STIMULANTS CARDIAQUES, GLUCOSIDES '
                         'CARDIOTONIQUES EXCLUS)'],
 'TRAITEMENT LAXATIF': ['A06A (MEDICAMENTS POUR LA CONSTIPATION)'],
 'TRAITEMENT MEDICAMENTEUX': ['D09A (PANSEMENTS MEDICAMENTEUX)'],
 'TRAITEMENT PSYCHOTROPES': ['N05C (HYPNOTIQUES ET SEDATIFS)',
                             'N05A (ANTIPSYCHOTIQUES)',
                             'N05B (ANXIOLYTIQUES)'],
 'TRANSFUSION': ['B05A (SANG ET DERIVES)'],
 'TTT ANTALGIQUE': ['N02A (OPIOIDES)',
                    'N02B (AUTRES ANALGESIQUES ET ANTIPYRETIQUES)',
                    'N02C (ANTIMIGRAINEUX)'],
 'TTT ANTIBIOTIQUE': ['J04AB (ANTIBIOTIQUES)',
                      'S01AA (ANTIBIOTIQUES)',
                      'J02AA (ANTIBIOTIQUES)',
                      'A07AA (ANTIBIOTIQUES)',
                      'G01AA (ANTIBIOTIQUES)'],
 'VACCIN ANTI GRIPPAL': ['J07BB (VACCINS ANTIGRIPPAUX)'],
 'VACCIN ANTIGRIPPAL': ['J07BB (VACCINS ANTIGRIPPAUX)'],
 'VACCINATION ANTI GRIPPALE': ['J07BB (VACCINS ANTIGRIPPAUX)'],
 'VACCINATION ANTI PNEUMOCOCCIQUE': ['J07AL (VACCINS ANTIPNEUMOCOCCIQUES)'],
 'VACCINATION ANTIGRIPPALE': ['J07BB (VACCINS ANTIGRIPPAUX)'],
 'VACCINATION ANTIGRIPPALE2018': ['J07BB (VACCINS ANTIGRIPPAUX)'],
 'VACCINATION ANTIPNEUMOCOCCIQUE': ['J07AL (VACCINS ANTIPNEUMOCOCCIQUES)'],
 'VIT B1': ['A11DA01 (THIAMINE (VIT B1))'],
 'VIT B12': ['B03BA (VITAMINE B12 (CYANOCOBALAMINE ET DERIVES))'],
 'VIT D': ['A11CC (VITAMINE D ET ANALOGUES)'],
 'VITAMINE': ['A11C (VITAMINES A ET D, ASSOCIATIONS DES DEUX INCLUSES)',
              'A11H (AUTRES PREPARATIONS VITAMINIQUES NON ASSOCIEES)',
              'A11D (VITAMINE B1 NON ASSOCIEE ET EN ASSOCIATION AVEC VITAMINES '
              'B6 ET B12)',
              'A11J (AUTRES MEDICAMENTS VITAMINIQUES, ASSOCIATIONS)',
              'A11G (ACIDE ASCORBIQUE (VIT C), ASSOCIATIONS INCLUSES)',
              'A11B (POLYVITAMINES NON ASSOCIEES)',
              'A11E (COMPLEXE VITAMINIQUE B, ASSOCIATIONS INCLUSES)',
              'A11A (POLYVITAMINES EN ASSOCIATION)',
              'B05XC (VITAMINES)'],
 'VITAMINE A': ['A11CA01 (RETINOL (VIT A))'],
 'VITAMINE B1': ['A11DA01 (THIAMINE (VIT B1))'],
 'VITAMINE B1 B6': ['A11DA01 (THIAMINE (VIT B1))',
                    'A11HA02 (PYRIDOXINE (VIT B6))'],
 'VITAMINE B12': ['B03BA (VITAMINE B12 (CYANOCOBALAMINE ET DERIVES))'],
 'VITAMINE B9': ['B03BB01 (FOLIQUE ACIDE)'],
 'VITAMINE D': ['A11CC (VITAMINE D ET ANALOGUES)'],
 'VITAMINE K': ['B02BA (VITAMINE K)'],
 'VITAMINES': ['A11C (VITAMINES A ET D, ASSOCIATIONS DES DEUX INCLUSES)',
               'A11H (AUTRES PREPARATIONS VITAMINIQUES NON ASSOCIEES)',
               'A11D (VITAMINE B1 NON ASSOCIEE ET EN ASSOCIATION AVEC '
               'VITAMINES B6 ET B12)',
               'A11J (AUTRES MEDICAMENTS VITAMINIQUES, ASSOCIATIONS)',
               'A11G (ACIDE ASCORBIQUE (VIT C), ASSOCIATIONS INCLUSES)',
               'A11B (POLYVITAMINES NON ASSOCIEES)',
               'A11E (COMPLEXE VITAMINIQUE B, ASSOCIATIONS INCLUSES)',
               'A11A (POLYVITAMINES EN ASSOCIATION)',
               'B05XC (VITAMINES)'],
 'VITAMINOTHERAPIE': ['A11C (VITAMINES A ET D, ASSOCIATIONS DES DEUX INCLUSES)',
                      'A11H (AUTRES PREPARATIONS VITAMINIQUES NON ASSOCIEES)',
                      'A11D (VITAMINE B1 NON ASSOCIEE ET EN ASSOCIATION AVEC '
                      'VITAMINES B6 ET B12)',
                      'A11J (AUTRES MEDICAMENTS VITAMINIQUES, ASSOCIATIONS)',
                      'A11G (ACIDE ASCORBIQUE (VIT C), ASSOCIATIONS INCLUSES)',
                      'A11B (POLYVITAMINES NON ASSOCIEES)',
                      'A11E (COMPLEXE VITAMINIQUE B, ASSOCIATIONS INCLUSES)',
                      'A11A (POLYVITAMINES EN ASSOCIATION)',
                      'B05XC (VITAMINES)']}