SECTION_DICT = {
    'antecedent': ['ANTECEDENTS MEDICAUX',
                'ANTÉCÉDENTS',
                'Antécédents médicaux et chirurgicaux',
                'ANTECEDENTS et HISTOIRE DE LA MALADIE',
                'ATCD:',
                'Antécédents chirurgicaux :',
                'Antécédent :',
                'Principaux antécédents et problèmes médicaux actuellement '
                'posés par le patient',
                'Allergie :',
                'ATCD med:',
                'Antécédents médicaux :',
                '4/ Antécédents, Autre(s) Maladie(s) en cours, Habitus, Mode '
                'de vie :',
                'Antécédents:',
                'Antécédents personnels',
                'Rappel des antécédents :',
                'Allergies',
                'Antécédents',
                'Principaux antécédents',
                'Allergies :',
                'FACTEURS DE RISQUES',
                'ANTÉCÉDENTS PERSONNELS',
                'ANTECEDENTS :',
                'RAPPEL DES ANTÉCÉDENTS ET HISTOIRE DE LA MALADIE',
                'FACTEURS DE RISQUE CARDIOVASCULAIRE :',
                'Facteurs de risque',
                'ANTECEDENTS ET PATHOLOGIES CHRONIQUES',
                'RESUME DES ANTECEDENTS',
                'ANTECEDENTS',
                'FACTEURS DE RISQUE CARDIOVASCULAIRES :',
                'ANTÉCÉDENTS MÉDICAUX ET CHIRURGICAUX',
                'ANTÉCÉDENTS :',
                'antécédents',
                'Facteurs de risque:',
                'ATCD :',
                'Facteurs de risques',
                'ANTECEDENTS PERSONNELS',
                'Antécédents somatiques :',
                'PRINCIPAUX ANTECEDENTS MEDICAUX et CHIRURGICAUX :',
                'Antécédents personnels :',
                'ATCD GYNECO:',
                'Antécédents :'],
 'antecedent_familiaux': ['Antécédents familiaux',
                          'Antécédent familial :',
                          'Antécédents familiaux :',
                          'ANTÉCÉDENTS FAMILIAUX'],
 'autre': ['INTERVENTION',
           'ANALYSE',
           'Rendez-vous de consultation post-opératoire :',
           'Pour mémoire :',
           'Réeducation à prévoir',
           'Médecin :',
           'ECG :',
           'Synthèse médicale :',
           'Service Demandeur :',
           'Évènements récents',
           'Planification des soins',
           'Synthèse clinico-biologique :',
           'PROJET DIAGNOSTIQUE ET THÉRAPEUTIQUE',
           'MODE DE SORTIE',
           'Résultat de la coronarographie',
           'Modifications thérapeutiques :',
           'ENQUETE DIETETIQUE :',
           'Suites opératoires :',
           'DEPISTAGES :',
           'Analyse',
           'hospitalisé dans le service de NEUROLOGIE_ADUL pour :',
           'Soins infirmiers',
           'Synthèse',
           'Prochains rendez-vous',
           'ÉVÉNEMENTS RÉCENTS',
           'SUIVI',
           'TSH :',
           'REEDUCATION-READAPTATION :',
           'DIAGNSOTICS REALISES AU COURS DE L’HOSPITALISATION :',
           'Synthèse initiale',
           'Contrôles biologiques :',
           "Technique d'enregistrement",
           'SUITES OPERATOIRES :',
           "A l'interrogatoire :",
           'OBJECTIFS GENERAUX DE LA PRISE EN CHARGE',
           'Appareillage',
           'HEMOPATHIE',
           'Evénement intercurrent',
           'Sommeil actuel',
           'TTT:',
           'Avis spécialisé',
           'Radiographie de contrôle :',
           'Développement psychomoteur',
           'Sérologies vaccinales',
           'Poids de sortie',
           'Chirurgicaux :',
           'Correspondant :',
           'EVENEMENTS RECENTS',
           'ENQUETE ACTIVITE PHYSIQUE :',
           'Résumé observation :',
           'Hospitalisations :',
           'Actes réalisés :',
           'SUITES POSTOPERATOIRES',
           'Destination de sortie',
           'Pathologies actives :',
           "Déroulement et résultat de l'angioplastie",
           'ENQUÊTE ACTIVITÉ PHYSIQUE :',
           "Indication de l'acte",
           'Mots clés :',
           'Résultats biologiques :',
           'NFS DE SORTIE',
           'ENTREE',
           'SUR LE PLAN PSYCHOLOGIQUE :',
           'CONTRÔLES SEROLOGIQUES :',
           'Kinésithérapie :',
           'SYNTHESE MEDICALE DIAGNOSTIQUE ET THERAPEUTIQUE :',
           'SYNTHESE MEDICALE',
           'INTERPRETATION',
           'Événements depuis la dernière visite',
           'INTERVENTION CHIRURGICALE :',
           'Documents de sortie',
           'Aux urgences:',
           'PLANIFICATION DES RENDEZ-VOUS',
           'PLANIFICATION DES SOINS / SUITES À DONNER',
           'PROCEDURE PRE-THERAPEUTIQUE',
           'PRISE EN CHARGE',
           'Synthèse générale',
           'INTERVENTION :',
           'Copie à :',
           'RESUME',
           'Suivi',
           'Technique',
           'INTERCURE',
           "Scores à l'entrée",
           'PMSI',
           'Familiaux',
           "L'ensemble des explorations réalisées ce jour retrouve :",
           'Evénements recensés au cours de ce séjour :',
           "Prise en charge à l'admission",
           'Pathologies intercurrentes :',
           'Signes fonctionnels',
           'Intervention(s) - acte(s) réalisé(s) :',
           'Contexte familial et social',
           'Mensurations de sortie',
           'Prise en charge :',
           'SUITES PREVUES :',
           'Actes réalisés',
           'PROJET THÉRAPEUTIQUE',
           'C ONDUITE THÉRAPEUTIQU E',
           'PROBLEMES PRIS EN CHARGE DANS LE SERVICE',
           'Projet thérapeutique à la sortie',
           'EVALUATION SOCIALE',
           'DESCRIPTION DETAILLEE',
           'Conseils',
           'Attitude thérapeutique initiale',
           "COMPTE-RENDU D'HOSPITALISATION :",
           'Dépistages',
           "A l'arrivée dans le service",
           'Nutrition',
           'PROPOSITION DE LA RCP',
           'Grossesse - Période néonatale',
           'Développement pubertaire',
           'ENQUÊTE DIÉTÉTIQUE :',
           'OBSERVATION',
           'POSE DE CATHETER CENTRAL',
           'Indication :',
           'STATUT FONCTIONNEL DE SORTIE',
           'Score de tri :',
           'Synthèse de la réeducation',
           'Projet thérapeutique',
           'SUIVI POSTOPERATOIRE :',
           'Interprétation :',
           'PROJET THERAPEUTIQUE',
           'Exploration du sommeil',
           'SYNTHÈSE MÉDICALE',
           'Données générales',
           'Orientation',
           'Croissance staturo-pondérale',
           'A son arrivée',
           'CORRESPONDANTS',
           'Points à surveiller',
           'Scores à la sortie'],
 'conclusion': ['SYNTÈSE MÉDICALE / CONCLUSION',
                'CONCLUSION :',
                'SYNTHESE MEDICALE/CONCLUSION',
                'Concl:',
                'Diagnostics :',
                'DIAGNOSTIC :',
                'CONSIGNES POST OP :',
                'Au total:',
                'Diagnostics retenus',
                'CONCLUSION DE SORTIE',
                'Au total :',
                'AU TOTAL',
                'Conclusion de sortie',
                'CONDUITE THÉRAPEUTIQUE :',
                'Diagnostic :',
                'Conduite à tenir :',
                'Diagnostics',
                'CAT:',
                'AU TOTAL :',
                "Conclusion à l'entrée",
                'Conclusion',
                'CONCLUSION D’ENTRÉE :',
                'Au total',
                'CONSIGNES A LA SORTIE',
                'AU TOTAL:',
                'DIAGNOSTIC RETENUS',
                'CONDUITE PRATIQUE :',
                'Diagnostic retenu',
                'DIAGNOSTIC',
                'CONCLUSION',
                'CAT :',
                'Conclusion :',
                'Diagnostics de sortie'],
 'evolution': ['Evolution dans le service:',
               'Evolution depuis la dernière consultation',
               'EVOLUTION DANS LE SERVICE',
               'EVOLUTION et CONCLUSION',
               'EVOLUTION',
               'ÉVOLUTION',
               'SUITES OPERATOIRES / EVOLUTION DANS LE SERVICE',
               'Evolution :',
               'Evolution dans le Service',
               'EVOLUTION :',
               'ÉVOLUTION :',
               'Evolution dans le service',
               'Evolution dans le service :',
               'Evolution',
               "Evolution durant l'hospitalisation"],
 'examen_clinique': ['Examen clinique',
                     "EXAMEN CLINIQUE A L'ENTRÉE",
                     "Examen clinique à l'arrivée",
                     "PARAMÈTRES VITAUX ET DONNÉES BIOMÉTRIQUES À L'ENTRÉE",
                     "Résultats d'examens",
                     'RAPPEL\nCLINIQUE',
                     'Résumé clinique :',
                     'Examens prescrits :',
                     'Examen clinique :',
                     'LE BILAN CLINIQUE AUX URGENCES A MONTRÉ :',
                     "Examen clinique à l'entrée :",
                     'Cliniquement :',
                     "Examen clinique à l'admission :",
                     "Paramètres vitaux, à l'accueil :",
                     "Données biométriques à l'entrée",
                     "EXAMEN CLINIQUE A L'ENTREE",
                     "PARAMÈTRES VITAUX ET DONNÉES BIOMÉTRIQUES A L'ENTRÉE",
                     'EXAMEN CLINIQUE :',
                     'Constantes de sortie :',
                     "Examen clinique à l'entrée",
                     "Données Biométriques à l'entrée",
                     'EXAMENS BIOLOGIQUES',
                     "Données biomètriques et paramètres vitaux à l'entrée",
                     'Examen clinique initial :',
                     'Examens para-cliniques',
                     "Paramètres vitaux à l'entrée",
                     'Clinique actuelle:',
                     'EXAMEN',
                     'Rappel clinique :',
                     'CONSTANTES DE SORTIE',
                     "EXAMEN CLINIQUE A L'ARRIVEE",
                     "EXAMEN CLINIQUE À L'ENTRÉE",
                     'Particularités cliniques et paracliniques',
                     "A L'EXAMEN CLINIQUE :",
                     'RAPPEL CLINIQUE:',
                     "Données biométriques et paramètres vitaux à l'entrée",
                     'Examen paraclinique :',
                     'Examen clinique :(?)',
                     "EXAMEN CLINIQUE À L'ARRIVÉE",
                     'La dernière évaluation clinique',
                     'Examen\nclinique :',
                     'A l’examen ce jour',
                     "Paramètres vitaux à l'accueil des urgences :",
                     'Examen clinique initial',
                     'Evolution clinique récente :',
                     'RAPPEL CLINIQUE',
                     'EXAMEN INITIAL :',
                     'DONNEES CLINIQUES',
                     "EXAMEN A L'ENTREE",
                     'Résumé clinique',
                     'Auscultation',
                     'EXAMEN CLINIQUE',
                     'A l’examen :',
                     'Clinique :',
                     "PARAMETRES VITAUX ET DONNEES BIOMETRIQUES A L'ENTREE",
                     'RAPPEL CLINIQUE :',
                     'Examen de sortie',
                     'CLINIQUE'],
 'examen_complementaire': ["Examens complémentaires à l'entrée",
                           'Biologie:',
                           'Biologie :',
                           'Examens complémentaires au cours du séjour',
                           'Autres examens complémentaires et évolution',
                           'Examen(s) complémentaire(s) :',
                           'EXAMENS COMPLEMENTAIRES',
                           'Bilan nutritionnel :',
                           'Examen complémentaire :',
                           'EXAMENS COMPLÉMENTAIRES RÉALISÉS PENDANT LE SÉJOUR',
                           'BILAN BIOLOGIQUE :',
                           'EXAMENS COMPLÉMENTAIRES',
                           "Bilan biologique à l'entrée",
                           'Biologie à l’entrée',
                           'EXAMEN COMPLEMENTAIRE',
                           'BIOCHIMIE',
                           'Examens complémentaires :',
                           'RADIOLOGIE :',
                           'Bilan extension :',
                           "Autres examens complémentaires à l'entrée",
                           'IMAGERIE :',
                           'BILAN PRÉOPÉRATOIRE :',
                           'EXAMENS COMPLÉMENTAIRES :',
                           'Bilan biologique :',
                           'BIOLOGIE :',
                           'Examens complémentaires',
                           "Résultats du bilan d'opérabilité :",
                           'EXAMENS COMPLEMENTAIRES :'],
 'histoire': ['Histoire récente de la maladie',
              'Histoire de la maladie actuelle',
              'HISTOIRE DU POIDS :',
              'Histoire de la maladie - Explorations',
              '5/ Histoire de la maladie',
              'Histoire récente',
              'HISTOIRE RECENTE',
              'Anamnèse',
              'HDM',
              'HISTOIRE DU DIABÈTE :',
              'Histoire de la Maladie:',
              'Histoire succincte de la maladie :',
              'ANAMNESE',
              'Histoire de la maladie :',
              'HDM:',
              '5/Histoire de la maladie :',
              'HISTOIRE RESUMEE DE LA MALADIE',
              'Histoire :',
              'HISTOIRE DU DIABETE :',
              "Résumé de l'histoire de la maladie",
              'HISTOIRE RECENTE MOTIVANT L’HOSPITALISATION',
              'HDM :',
              'Histoire de la maladie',
              'HISTOIRE RECENTE DE LA MALADIE :',
              'Histoire de la Maladie :',
              'HISTOIRE DE LA MALADIE'],
 'mode_de_vie': ['MODE DE VIE :',
                 'Mode de vie - Scolarité',
                 'MODE DE VIE',
                 'Mode de vie',
                 'HABITUS',
                 'Situation sociale, mode de vie',
                 'HABITUS :',
                 'Mode de vie :',
                 'Mode de vie antérieur :',
                 'Habitus'],
 'motif': ['Motif médical',
           "MOTIF DE L'EXAMEN",
           "motif d'hospitalisation:",
           "MOTIF DE L'EXAMEN :",
           'MOTIF',
           "MOTIF D'INTERVENTION",
           "Motif de l'hospitalisation",
           "MOTIF D'HOSPITALISATION :",
           'Motif de consultation :',
           'Motif de tri :',
           'Motif de la consultation :',
           "Motif d'Hospitalisation :",
           "MOTIF D'HOSPITALISATION",
           "MOTIF DE L'HOSPITALISATION :",
           "Motif d'hospitalisation",
           'MOTIF D’HOSPITALISATION :',
           'motif suivant :',
           "Motif de l'hospitalisation :",
           "Motif de l'examen",
           'Motif :',
           'Motif de la première consultation',
           'MOTIF d’HOSPITALISATION :',
           'MOTIF :',
           'Motif d’hospitalisation :',
           'Motif'],
 'traitement': ['Traitements :',
                'Demandes et prescriptions externes',
                'Prescriptions aux urgences',
                'TRAITEMENTS :',
                'Traitements associés',
                'TRAITEMENT :',
                'Traitement',
                'PROTOCOLE DE TRAITEMENT',
                'Traitement :'],
 'traitement_entree': ["TRAITEMENT A L'ENTRAÉE",
                       'TRAITEMENTS HABITUELS:',
                       'Vaccinations :',
                       'Traitement en cours :',
                       'Vaccinations',
                       'Traitement depuis la dernière visite',
                       'TRAITEMENTS A L’ENTREE',
                       'Traitement au domicile :',
                       "TRAITEMENT D'ENTRÉE :",
                       'TRAITEMENT A L’ARRIVEE',
                       "TRAITEMENT À L'ENTRÉE",
                       'Traitement en cours',
                       'TRAITEMENT ACTUEL :',
                       'Traitements en cours :',
                       "TRAITEMENT A L'ENTREE",
                       'Traitement actuel',
                       'Traitements habituels :',
                       'TRAITEMENT EN COURS',
                       "TRAITEMENT A L'ENTRÉE",
                       "Traitement à l'entrée:",
                       "Traitements à l'entrée",
                       "Traitement d'entrée :",
                       'TRAITEMENT HABITUEL :',
                       'Traitements actuels',
                       'VACCINATIONS :',
                       "Traitement à l'entrée",
                       'Traitement actuel :',
                       'VACCINATIONS',
                       'Traitement habituel :',
                       'Traitements habituels',
                       'TRAITEMENT HABITUEL'],
 'traitement_sortie': ['TRAITEMENT DE SORTIE',
                       "Traitement à l'issue de la consultation",
                       'Prescriptions médicales de sortie',
                       'Traitement de sortie',
                       'Prescriptions médicales de sortie :',
                       'Traitement de sortie :',
                       'Traitement et consignes de sortie :',
                       'Prescriptions de sortie :']}